### ISSUE TITLE
Pokemon Legends: Arceus - 01001F5010DFA000

### ISSUE THREAD

**Issue by jd-apprentice** [Ryujinx/Ryujinx-Games-List#3821] opened 2022-01-29 17:24 UTC
#### Current on `master` : 1.1.0+66dd3500

- Game is working fine, I just find this issue where you throw an agile or strong attack and it gliches with 3 big squares

#### Pull requests needed :

- [For running the game in the first place](https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424)

#### Screenshots :

![ryujinx_capture_2022-01-29_14-16-37](https://user-images.githubusercontent.com/68082746/151670775-b08c0d3b-b1a5-4848-a8a0-59a2a2c903ee.png)

**Comment by MutantAura** [comment] 2022-01-29 17:25
Duplicate of #3817

**Closed by MutantAura** 2022-01-29 17:25 UTC
