### ISSUE TITLE
Nintendo Switch Sports - 0100D2F00D5C0000

### ISSUE THREAD

**Issue by Hariesap** [Ryujinx/Ryujinx-Games-List#4892] opened 2024-03-12 02:29 UTC
### Game Name

Nintendo Switch Sports - 0100D2F00D5C0000

### Game Update Version

1.4.0

### Emulator Build Version

1.1.1224

### Graphics Backend

Vulkan

### Hardware Specs

-  CPU: i7-6700
-  GPU: NVIDIA RTX 2070
-  RAM: 16GB

### Game State

game black screen and stop close

**Comment by MutantAura** [comment] 2024-03-12 02:29
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4079

**Closed by MutantAura** 2024-03-12 02:29 UTC
