### ISSUE TITLE
Brigandine: The Legend of Runersia - 010011000EA7A000

### ISSUE THREAD

**Issue by taiwan-king** [Ryujinx/Ryujinx-Games-List#3403] opened 2021-02-19 15:01 UTC
Brigandine: The Legend of Runersia

Game Update Version : 1.1.4
Current on master : 1.0.6045

The game can run normally to the end.

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

Screenshots :
![1613746159621](https://user-images.githubusercontent.com/24381898/108520724-f527f780-7305-11eb-989f-f131d651205a.jpg)
![1613746289952](https://user-images.githubusercontent.com/24381898/108520728-f6592480-7305-11eb-9b67-0e9f786bb2fd.jpg)
![1613745319241](https://user-images.githubusercontent.com/24381898/108520734-f6f1bb00-7305-11eb-8282-fc0a15c35733.jpg)
![1613745671065](https://user-images.githubusercontent.com/24381898/108520740-f78a5180-7305-11eb-8c72-88e2c2bfb416.jpg)

Log:
[Ryujinx_1.0.6604_2021-02-19_22-21-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6010813/Ryujinx_1.0.6604_2021-02-19_22-21-58.log)

**Comment by Cronos-0** [comment] 2021-02-19 15:07
duplicate of  #1851

**Closed** 2021-02-19 15:31 UTC

**Comment by EmulationFanatic** [comment] 2021-02-19 15:34
Copied data to existing issue.
