### ISSUE TITLE
Vengeful Guardian: Moonrider - Game doesnt start and Ryujinx doesn't install the title update

### ISSUE THREAD

**Issue by legolas119** [Ryujinx/Ryujinx-Games-List#4902] opened 2024-03-17 14:09 UTC
### Game Name

Vengeful Guardian: Moonrider

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1239

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *AMD Ryzen 3700X*
- ##### GPU: *RTX 2060 Super*
- ##### GPU Driver version: *551.76*
- ##### RAM: *2 x 8 GB Kingston HyperX Predator 3200-16*

### Game State

Running the game, it appears "The Arcade Crew" title and then "The Joymascher". After that it appears a white screen and the game freezes. I tried both with Vulkan and OpenGL.
In addition, RyuJinx doesn't accept the title update of this game, see error message below.

### Screenshots

![Cattura2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/48774386/f14a7d2f-aae9-4007-89f4-85e8c5cd626d)
![Cattura3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/48774386/d0d4ce3d-80c5-4ed9-9249-79ea16f28bb1)

### Log File

[Ryujinx_1.1.1239_2024-03-17_15-00-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14627610/Ryujinx_1.1.1239_2024-03-17_15-00-46.log)

**Comment by piplup55** [comment] 2024-03-17 19:27
duplicate of #4358

**Closed by piplup55** 2024-03-17 19:27 UTC
