### ISSUE TITLE
Bjorn29512 

### ISSUE THREAD

**Issue by HikariTM** [Ryujinx/Ryujinx-Games-List#4553] opened 2023-04-16 16:48 UTC
### Game Name

Yo-Kai Watch 4++

### Game Update Version

2.2.0

### Emulator Build Version

1.1.662

### Graphics Backend

Vulkan

### Hardware Specs

CPU: i5-12400f

GPU: NVIDIA GTX 1660 Super (Driver Ver. 531.18)

RAM: 32GB

### Game State

Runs smoothly and as intended on Vulkan with no noticeable issues.

### Screenshots

![image](https://user-images.githubusercontent.com/130921972/232327448-957e0d5b-97da-4197-b9b0-91516ac4471e.png)
![image](https://user-images.githubusercontent.com/130921972/232327550-9ecc20f2-e159-4073-a0a5-6b79e57bc105.png)
![image](https://user-images.githubusercontent.com/130921972/232327558-6bdea8ad-a1b9-4fab-b5e2-6a4874e2cc51.png)
![image](https://user-images.githubusercontent.com/130921972/232327571-491c81e8-4f2b-46f1-95a3-0f1de63c1290.png)
![image](https://user-images.githubusercontent.com/130921972/232327604-ec9e7859-d539-48ec-92d0-353044fea7e6.png)

### Log File

No response

**Comment by MetrosexualGarbodor** [comment] 2023-04-16 16:53
Duplicate of  #4494.

**Closed by MetrosexualGarbodor** 2023-04-16 16:53 UTC
