### ISSUE TITLE
Touhou Gouyoku Ibun　～ Sunken Fossil World. - 0100031018CFE000

### ISSUE THREAD

**Issue by doremyy** [Ryujinx/Ryujinx-Games-List#4563] opened 2023-04-20 22:15 UTC
### Game Name

Touhou Gouyoku Ibun　～ Sunken Fossil World.

### Game Update Version

1.1.0

### Emulator Build Version

1.1.0-macos1

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Apple M2*
- ##### GPU: *Apple M2*
- ##### RAM: *8GB*

### Game State

boots, but soon after crashes. can't quite make it to the title screen.

### Log File

[Ryujinx_ 1.1.0-macos1_2023-04-20_18-00-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11290789/Ryujinx_.1.1.0-macos1_2023-04-20_18-00-54.log)

**Comment by MetrosexualGarbodor** [comment] 2023-04-20 22:18
Duplicate of #4480

**Closed by MetrosexualGarbodor** 2023-04-20 22:18 UTC
