### ISSUE TITLE
Animal Crossing Crashing at Startup

### ISSUE THREAD

**Issue by Syndicateeee** [Ryujinx/Ryujinx-Games-List#1049] opened 2020-05-03 11:09 UTC
Animal Crossing

Build Version 1.0.4427

The Game is working for about 5 seconds on the Entry Screen then it crashes.

The Console Log gave me this:

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.NvGpuFifo.SendMacroCodeData(Int32 index, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 155
   at Ryujinx.Graphics.Gpu.Engine.Methods.SendMacroCodeData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodFifo.cs:line 32
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by HorrorTroll** [comment] 2020-05-03 11:11
Duplicate of #250

**Closed by HorrorTroll** 2020-05-03 11:11 UTC
