### ISSUE TITLE
Barbearian - 0100F7E01308C000

### ISSUE THREAD

**Issue by taiwan-king** [Ryujinx/Ryujinx-Games-List#3402] opened 2021-02-19 14:25 UTC
## Barbearian

Game Update Version : 1.0.11
Current on master : 1.0.6604

The menu shows some abnormalities and the game is completely normal until the level is cleared. 

#### Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

#### Screenshots:
![1613744369426](https://user-images.githubusercontent.com/24381898/108516532-4e415c80-7301-11eb-8d19-37758da324f0.jpg)
![1613744390894](https://user-images.githubusercontent.com/24381898/108516537-4f728980-7301-11eb-8090-2feeb29cf2d1.jpg)
![1613744304330](https://user-images.githubusercontent.com/24381898/108516540-500b2000-7301-11eb-9125-eeb906135018.jpg)

#### Log:
[Ryujinx_1.0.6604_2021-02-19_22-01-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6010595/Ryujinx_1.0.6604_2021-02-19_22-01-15.log)

**Comment by EmulationFanatic** [comment] 2021-02-19 14:33
Thanks for these tests! Please follow the template formatting and include your GPU model so that the issue does not have to be modified after your submisson.

**Comment by LukeWarnut** [comment] 2021-02-19 16:12
This is a duplicate of #2819

**Comment by EmulationFanatic** [comment] 2021-02-19 16:17
Copied data to existing issue. Closed as duplicate.

**Closed by EmulationFanatic** 2021-02-19 16:17 UTC
Labels: duplicate
