### ISSUE TITLE
Bayonetta 3 ch14 credits sequence freeze

### ISSUE THREAD

**Issue by CamperArts** [Ryujinx/Ryujinx-Games-List#4679] opened 2023-07-09 14:56 UTC
### Game Name

Bayonetta 3

### Game Update Version

1.2.0

### Emulator Build Version

1.1.956

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Intel Core i5 4460
- ##### GPU: NVIDIA GeForce GTX 1050 Ti
- ##### RAM: DDR3 12 GBytes 3399.2 MHz

### Game State

At the final verse game freezes and don't allows to complete section normally
That problem is on all builds and versions of the game and emulator. Disabling texture recompression helps a little but causes crashes

### Screenshots

https://youtu.be/kMGUIOO4fAs

### Log File

[Ryujinx_1.1.956_2023-07-09_17-37-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11995438/Ryujinx_1.1.956_2023-07-09_17-37-43.log)

**Comment by MetrosexualGarbodor** [comment] 2023-07-09 15:02
Your log is empty. Please join Discord for support queries: https://discord.gg/ryujinx
Closing as duplicate of #4129

**Closed by MetrosexualGarbodor** 2023-07-09 15:02 UTC

**Comment by CamperArts** [comment] 2023-07-09 18:01
> Your log is empty. Please join Discord for support queries: https://discord.gg/ryujinx Closing as duplicate of #4129

this is not copy, because no one complained on this problem

**Comment by CamperArts** [comment] 2023-07-09 18:17
> Your log is empty. Please join Discord for support queries: https://discord.gg/ryujinx Closing as duplicate of #4129

[Ryujinx_1.1.956_2023-07-09_21-01-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11995834/Ryujinx_1.1.956_2023-07-09_21-01-54.log)
