### ISSUE TITLE
perfomance on a ryzen 5 3500 and gtx1650

### ISSUE THREAD

**Issue by Goti11** [Ryujinx/Ryujinx-Games-List#4610] opened 2023-05-15 16:55 UTC
### Game Name

legend of zelda TEARS OF THE KINGDOM

### Game Update Version

1.1.0

### Emulator Build Version

1.1.800

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### RAM: *(e.g. 16GB)*
CPU: RYZEN 5 3500 
GPU:GTX 1650(4GB)
RAM:8GB 2999MHZ

### Game State

30FPS CONSTANT IN 720P

**Comment by MetrosexualGarbodor** [comment] 2023-05-15 17:09
Duplicate of #4598

**Closed** 2023-05-15 17:09 UTC
