### ISSUE TITLE
Miitopia - 01003DA010E8A000

### ISSUE THREAD

**Issue by josedanielsteller** [Ryujinx/Ryujinx-Games-List#4123] opened 2022-10-28 00:36 UTC
#### Graphics Backend : *OpenGL*

For some reason, the Squire Sword has a shader issue--if it appears, its shiny gray shader is also applied to the armor.
[Recently restarted my save file, so I don't know if the same happens with other armors.]

#### Screenshots :

This is what it should look like [the issue doesn't happen with weapons other than the Squire Sword]:
![ryujinx_capture_2022-10-27_18-28-00](https://user-images.githubusercontent.com/69710618/198422144-663a7514-91e9-4685-a906-6b64b99d67e2.png)

This is what it looks like instead:
![ryujinx_capture_2022-10-27_18-27-39](https://user-images.githubusercontent.com/69710618/198422186-c4a813fb-381f-497b-bed7-085b78c45ca6.png)

**Comment by MetrosexualGarbodor** [comment] 2022-10-28 00:39
Duplicate of #3644

**Comment by josedanielsteller** [comment] 2022-10-28 00:40
Oh.

**Closed by MetrosexualGarbodor** 2022-10-28 00:39 UTC
