### ISSUE TITLE
Splatoon 2 early crash

### ISSUE THREAD

**Issue by yim0000** [Ryujinx/Ryujinx-Games-List#4341] opened 2023-01-07 07:48 UTC
## Game Name
splatoon 2

#### Game Update Version: *(e.g. 1.0.0 or 1.1.3)*
5.5.1

#### Emulator Build Version: *(e.g. 1.1.373)*
1.1.0-macos1

#### Graphics Backend: *(e.g. Vulkan or OpenGL)*
Vulkan

##### RAM: 8GB

*Describe the current game state here. 
The game simply just runs and loads, but it usually crashes during or right after the tutorial, and never made pass it.
I have read the past issues and found sometime about controller issues, but I only have one controller active, and I don't seem to find anything else reading the past issues. The app itself crashes/Quit unexpectedly. Its seems to me that its a controller issue same as a past issue but something else is in the log file and is not the same as the past issue posted.

#### Log file:

*Add a log file here. 
Can be found in the logs folder, in the same directory as the Ryujinx executable, or through File > Open logs folder.*
[Ryujinx_ 1.1.0-macos1_2023-01-05_06-23-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10365731/Ryujinx_.1.1.0-macos1_2023-01-05_06-23-45.log)

**Comment by MetrosexualGarbodor** [comment] 2023-01-07 07:52
Duplicate of #703

**Closed by MetrosexualGarbodor** 2023-01-07 07:52 UTC
