### ISSUE TITLE
Very Low FPS

### ISSUE THREAD

**Issue by LuisC2872** [Ryujinx/Ryujinx-Games-List#4921] opened 2024-04-01 17:20 UTC
### Game Name

The Legends Of Zelda : Tears Of The Kingdom

### Game Update Version

1.2.1

### Emulator Build Version

1.1.1248

### Graphics Backend

Vulkan

### Hardware Specs

Version: 1.1.1248
CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
GPU: Intel ARC 4 GB
RAM: 5018/7885 MiB
OS: Microsoft Windows 10.0.19045 (X64)

System Settings
Audio Backend: SDL2
Console Mode: Handheld
PPTC Cache: Enabled
Shader Cache: Enabled
V-Sync: Disabled
Graphics Settings
Graphics Backend: Vulkan
Resolution: Native (720p/1080p)
Anisotropic Filtering: Auto
Aspect Ratio: 16:9
Texture Recompression: Enabled

### Game State

Good afternoon, could someone here help me figure out the correct configuration to be able to emulate Zelda at a decent fps rate in Ryujinx. I don't understand why it doesn't go above 15 fps and I've tried everything.

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/57243602/aa362f00-4c5e-4cbb-8cff-d0e4f93e8864)

### Log File

[Ryujinx_1.1.1248_2024-04-01_12-39-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14826689/Ryujinx_1.1.1248_2024-04-01_12-39-01.log)

**Comment by piplup55** [comment] 2024-04-01 17:54
duplicate of #4598, and you were already told on discord your pc isn't good enough

**Closed by piplup55** 2024-04-01 17:54 UTC
