### ISSUE TITLE
eBaseball Powerful Pro Yakyuu 2020 - 010073000FE18000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#3242] opened 2021-01-09 22:17 UTC
#### Current on `master` : 1.0.6260

Crashes on launch 

```
00:00:22.794 |E| HLE.OsThread.9 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Hid.IHidServer: 134

Guest Stack Trace:
Process: Service, PID: 86

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  86 00 00 00 00 00 00 00   SFCI···········
00000010   01 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000020   00 00 00 00                                        ····   

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Outstanding Issues :

https://github.com/Ryujinx/Ryujinx/issues/1891

#### Logs :

[Ryujinx_1.0.6260_2021-01-10_05-09-48.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5791911/Ryujinx_1.0.6260_2021-01-10_05-09-48.log)

**Comment by benderscruffy** [comment] 2022-02-12 00:03
using 1.1.26
if you tick ignore missing services 
goes ingame
graphic glitches with the players and the crowd
![ryujinx_capture_2022-02-12_07-57-57](https://user-images.githubusercontent.com/2696404/153686647-0b467df3-788c-481b-bfd2-4dcdfd6bd2f6.png)
![ryujinx_capture_2022-02-12_07-58-03](https://user-images.githubusercontent.com/2696404/153686648-1cd0aed1-6e3a-4752-9ddc-8dabbec4f324.png)
![ryujinx_capture_2022-02-12_07-58-05](https://user-images.githubusercontent.com/2696404/153686649-5533103e-5952-42a5-919c-237a2c3d97c5.png)
![ryujinx_capture_2022-02-12_07-58-07](https://user-images.githubusercontent.com/2696404/153686653-15f62b55-a559-4b45-973b-e3d50775f222.png)
![ryujinx_capture_2022-02-12_07-58-10](https://user-images.githubusercontent.com/2696404/153686655-a31d62ea-f7a2-443b-b7d4-15869133114d.png)
![ryujinx_capture_2022-02-12_07-58-33](https://user-images.githubusercontent.com/2696404/153686657-38f45b07-a99a-441e-bcff-587b7c7ffa31.png)
![ryujinx_capture_2022-02-12_07-58-41](https://user-images.githubusercontent.com/2696404/153686661-683c2f5f-c5fd-483f-b45b-a0c76ec16b2b.png)
![ryujinx_capture_2022-02-12_07-58-43](https://user-images.githubusercontent.com/2696404/153686663-137fe195-2a50-4624-bd2d-8047d3b2f4c1.png)
![ryujinx_capture_2022-02-12_07-58-57](https://user-images.githubusercontent.com/2696404/153686670-a8f24cdf-be13-4923-a591-fad445cc3255.png)
![ryujinx_capture_2022-02-12_07-59-16](https://user-images.githubusercontent.com/2696404/153686677-8f93b982-1345-4e72-a3d2-2c3941269586.png)
![ryujinx_capture_2022-02-12_07-59-25](https://user-images.githubusercontent.com/2696404/153686681-9d0b820f-ea7a-4d3a-9795-f5ec7513bafc.png)
![ryujinx_capture_2022-02-12_07-59-36](https://user-images.githubusercontent.com/2696404/153686685-07cf7fcd-842f-4143-ba57-19d8648eebf1.png)
![ryujinx_capture_2022-02-12_07-59-53](https://user-images.githubusercontent.com/2696404/153686688-870abf93-3a70-44d5-b0c8-15e5b0b35c78.png)
![ryujinx_capture_2022-02-12_08-00-07](https://user-images.githubusercontent.com/2696404/153686695-f31cd6df-4baf-4590-a82b-f0b2d788f07d.png)
![ryujinx_capture_2022-02-12_08-00-17](https://user-images.githubusercontent.com/2696404/153686703-bc6b64b1-0165-41b7-81a3-4167f0a72ee1.png)
![ryujinx_capture_2022-02-12_08-00-21](https://user-images.githubusercontent.com/2696404/153686705-54ed4687-0f76-4dfa-b98b-551350fc8d1b.png)
![ryujinx_capture_2022-02-12_08-00-26](https://user-images.githubusercontent.com/2696404/153686706-3564844a-4fc1-40d5-bf6e-118bc6ca3f60.png)
![ryujinx_capture_2022-02-12_08-00-46](https://user-images.githubusercontent.com/2696404/153686710-b778f24e-8f9f-4742-9fe0-4906fb1d9595.png)

**Comment by EmulationFanatic** [comment] 2022-08-28 12:12
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/2355

**Closed by EmulationFanatic** 2022-08-28 12:12 UTC
Labels: gpu, services, status-ingame, crash
