### ISSUE TITLE
Graphic problem

### ISSUE THREAD

**Issue by kogoyodemota** [Ryujinx/Ryujinx-Games-List#4671] opened 2023-07-03 15:42 UTC
### Game Name

the legend of Zelda: Tears of the Kingdom

### Game Update Version

11.2

### Emulator Build Version

1.1.951

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz   3.80 GHz
- ##### GPU: Radeon (TM) RX 460 Graphics
- ##### RAM: 16GB

### Game State

Using Vulkan 

### Screenshots

![ryujinx](https://github.com/Ryujinx/Ryujinx-Games-List/assets/138509100/a2a9e788-f6d5-4915-8ce1-9a133adf3e3d)

### Log File

[Ryujinx_1.1.951_2023-07-03_12-13-34.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11938393/Ryujinx_1.1.951_2023-07-03_12-13-34.log)

**Comment by MetrosexualGarbodor** [comment] 2023-07-03 23:24
This is already known and has been posted on the main issue. Closing as duplicate of #4598.

**Closed by MetrosexualGarbodor** 2023-07-03 23:24 UTC
