### ISSUE TITLE
Skyward Sword HD Audio Quality Issue

### ISSUE THREAD

**Issue by nashlaga** [Ryujinx/Ryujinx-Games-List#3658] opened 2021-07-19 22:07 UTC
The Legend of Zelda: Skyward Sword

Game Update Version : 1.0.0

Ryujinx Version 1.0.6973

Majority of the audio including music seems to be playing at a lowered bit depth or sample rate, 

Hardware Specs : 

CPU: Ryzen 5600x
GPU: NVIDIA RTX 3070
RAM: 32GB DDR4

**Comment by AcK77** [comment] 2021-07-19 22:20
Duplicate of #3657, comment your feedback there if needed. Thanks.

**Closed by AcK77** 2021-07-19 22:20 UTC
