### ISSUE TITLE
Higurashi no Naku Koro ni Hou

### ISSUE THREAD

**Issue by DemiurgeZ** [Ryujinx/Ryujinx-Games-List#3014] opened 2020-12-13 11:21 UTC
#### Current on `master` : 1.0.6051

Audio plays extremely intermittently, especially for the Opening CG; Crashes after clicking the "Settings" on the main interface of the game.

```
Last error returned:
Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
```

#### Log file :

[Ryujinx_1.0.6051_2020-12-13_18-53-20.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5684506/Ryujinx_1.0.6051_2020-12-13_18-53-20.log)

**Comment by SeraUQ** [comment] 2020-12-13 11:40
closed as duplicate of #66

**Closed by SeraUQ** 2020-12-13 11:40 UTC
