### ISSUE TITLE
Sand textures bug ( The Legend Of Zelda: Skyward Sword HD )

### ISSUE THREAD

**Issue by LuisC2872** [Ryujinx/Ryujinx-Games-List#4909] opened 2024-03-24 12:16 UTC
### Game Name

The Legend Of Zelda: Skyward Sword HD

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1244 

### Graphics Backend

Vulkan

### Hardware Specs

Version: 1.1.1244 
CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz 
GPU: Intel ARC 4 GB
RAM: 5018/7885 MiB
OS: Microsoft Windows 10.0.19045 (X64)

System Settings
Audio Backend: SDL2
Console Mode: Docked
PPTC Cache: Enabled
Shader Cache: Enabled
V-Sync: Enabled
Graphics Settings
Graphics Backend: Vulkan
Resolution: Native (720p/1080p)
Anisotropic Filtering: Auto
Aspect Ratio: 16:9
Texture Recompression: Enabled

### Game State

The game runs very well at 60 fps but has a problem with the sand textures when they fall in a cascade, the same thing happens with the water waterfalls which are reflected as squares instead of coming out normally.

### Screenshots

![The Legend of Zelda_ Skyward Sword HD_2024-03-23_19-12-08](https://github.com/Ryujinx/Ryujinx-Games-List/assets/57243602/bd00efe1-9cf0-4688-8532-512c9fec64d5)
![The Legend of Zelda_ Skyward Sword HD_2024-03-23_19-12-16](https://github.com/Ryujinx/Ryujinx-Games-List/assets/57243602/f43523ca-c47a-4d7f-9d77-5c5dcbc71d3b)
![The Legend of Zelda_ Skyward Sword HD_2024-03-23_19-12-23](https://github.com/Ryujinx/Ryujinx-Games-List/assets/57243602/712a4340-acdf-428d-85b5-c1dbfaef4326)

### Log File

[Ryujinx_1.1.1244_2024-03-23_19-49-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14735405/Ryujinx_1.1.1244_2024-03-23_19-49-30.log)

**Comment by piplup55** [comment] 2024-03-24 12:17
duplicate of #3657

**Closed by piplup55** 2024-03-24 12:17 UTC
