### ISSUE TITLE
Zelda Echoes of Wisdom crashes during loading, after guards scene

### ISSUE THREAD

**Issue by SailVerala** [Ryujinx/Ryujinx-Games-List#5076] opened 2024-09-28 14:05 UTC
### Game Name

The Legend of Zelda: Echoes of Wisdom

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1401

### Graphics Backend

Vulkan

### Hardware Specs

- CPU: AMD Ryzen 9 7900X3D
- GPU: AMD RX 7900 XTX
- GPU Driver version: AE 24.5.1
- RAM: 32GB

### Game State

After the cutscene where Zelda meets her guards, the game goes into a loading screen just before she meets up with the townsfolk. It's during this loading when the emulator crashes. I tried both Vulkan and OpenGL, but both crash at the exact moment. The game runs pretty fine up until the crashing. I tried Changing some settings around but it still crashes.

### Screenshots

![Screenshot 2024-09-28 100201](https://github.com/user-attachments/assets/7b09f5d5-3d8f-4f7d-9fc1-0eacc411cac9)
![Screenshot 2024-09-28 100213](https://github.com/user-attachments/assets/936bb9dd-66a1-418f-bb30-21af3d575251)
![Screenshot 2024-09-28 100228](https://github.com/user-attachments/assets/9f5dc054-c84a-43ba-8bbb-27d901570718)
![Screenshot 2024-09-28 100238](https://github.com/user-attachments/assets/cee6641f-9381-45ce-91bc-ba20482f2ed6)

### Log File

[Ryujinx_1.1.1401_2024-09-28_09-57-48.log](https://github.com/user-attachments/files/17174617/Ryujinx_1.1.1401_2024-09-28_09-57-48.log)

**Comment by piplup55** [comment] 2024-09-28 15:02
Duplicate of #5070

**Closed by piplup55** 2024-09-28 15:02 UTC
