### ISSUE TITLE
Impossible)ryujinx ebaseball powerful proyakyu 2022 

### ISSUE THREAD

**Issue by yeunhari** [Ryujinx/Ryujinx-Games-List#4614] opened 2023-05-17 00:21 UTC
### Game Name

ebaseball powerful proyakyu 2022 

### Game Update Version

1.8

### Emulator Build Version

1.1.0

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(i5-10400F)*
- ##### GPU: *(NVIDIA GTX 1050ti)*
- ##### RAM: *(32GB)*

### Game State

When I press run game, a red phrase appears in the log and closes

### Log File

[Ryujinx_1.1.0+4513dba_2023-05-17_09-10-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11493052/Ryujinx_1.1.0%2B4513dba_2023-05-17_09-10-55.log)

**Comment by AcK77** [comment] 2023-05-17 00:32
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4010

**Closed by AcK77** 2023-05-17 00:32 UTC
