### ISSUE TITLE
Lynel Crash Ryujinx on The Legend of Zelda Breath of The Wild

### ISSUE THREAD

**Issue by DenisNinja** [Ryujinx/Ryujinx-Games-List#4534] opened 2023-04-01 16:01 UTC
### Game Name

The Legend of Zelda Breath of The Wild

### Game Update Version

1.6.0

### Emulator Build Version

1.1.689

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. AMD Ryzen 9 5950X)*
- ##### GPU: *(e.g. NVIDIA RTX 2070 Super XC Ultra)*
- ##### RAM: *(e.g. 32GB)*

### Game State

Whenever Link is fighting against a Lynel, or is close to a Lynel, the game Zelda Breath of the Wild Crash Ryujinx, this happened in all versions of Ryujinx and it doesn't matter the configuration, I got tired of testing and configuring, When Ryujinx crashes, it loses your fatal logs errors etc

**Comment by Bjorn29512** [comment] 2023-04-01 16:03
Duplicate of #86  also this issue is fixed by PR #4618 so wait for it to merge.

**Closed** 2023-04-01 16:04 UTC
