### ISSUE TITLE
Game Crashes when in depths

### ISSUE THREAD

**Issue by MysticStar32** [Ryujinx/Ryujinx-Games-List#4628] opened 2023-05-29 15:50 UTC
### Game Name

Zelda Tears of the Kingdom

### Game Update Version

1.1.2

### Emulator Build Version

1.1.841

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Ryzen 5 5600x
- ##### GPU: AMD Radeon RX 580 4gb
- ##### RAM: 32GB

### Game State

Once I drop into the depths shortly after the game crashes.  I have noticed that if I play the game in OpenGL in the depths, it won't crash, but the game is super slow and a lot of the ground is static and pixelated.  I played the entire Goron questline in OpenGL and it was definitely not the best experience. I'm not sure if it is a corrupted game file or a problem with RAM. I would put screenshots but the game just crashes so I really can't.

### Log File

[Ryujinx_1.1.841_2023-05-29_10-38-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11592909/Ryujinx_1.1.841_2023-05-29_10-38-12.log)
[Ryujinx_1.1.841_2023-05-29_10-44-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11592910/Ryujinx_1.1.841_2023-05-29_10-44-40.log)
[Ryujinx_1.1.841_2023-05-29_01-34-39.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11592911/Ryujinx_1.1.841_2023-05-29_01-34-39.log)

**Comment by ashpart** [comment] 2023-05-31 04:41
Turn on texture recompression in video options. There's gonna be lag stutters dropping down, but the game will stop crashing in 1-3 tries.
![My settings; doesn't crash on vulkan](https://github.com/Ryujinx/Ryujinx-Games-List/assets/115097912/b86bd5b3-845b-4f31-9010-92f51ef5c3f3)

**Comment by MetrosexualGarbodor** [comment] 2023-05-31 16:29
Closing as duplicate of #4598.

**Closed by MetrosexualGarbodor** 2023-05-31 16:29 UTC
