### ISSUE TITLE
Lazer Kitty Pow! Pow!

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#2298] opened 2020-08-09 15:04 UTC
#### Current on `master` : 1.0.5152

Game played great without problems

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-08-09 21-33-53-146](https://user-images.githubusercontent.com/35269098/89735357-348aa700-da8c-11ea-8d86-c52bbaee1f39.jpg)
![bandicam 2020-08-09 21-37-45-859](https://user-images.githubusercontent.com/35269098/89735358-38b6c480-da8c-11ea-9a4b-38a75c05a9f3.jpg)
![bandicam 2020-08-09 21-34-22-412](https://user-images.githubusercontent.com/35269098/89735361-3d7b7880-da8c-11ea-873a-118d8e091ee3.jpg)
![bandicam 2020-08-09 21-34-35-842](https://user-images.githubusercontent.com/35269098/89735363-4409f000-da8c-11ea-8395-84f299f78efd.jpg)
![bandicam 2020-08-09 21-34-43-037](https://user-images.githubusercontent.com/35269098/89735364-466c4a00-da8c-11ea-99ce-64ac0530058a.jpg)
![bandicam 2020-08-09 21-35-22-578](https://user-images.githubusercontent.com/35269098/89735369-4bc99480-da8c-11ea-94b3-8882e01ac0a7.jpg)
![bandicam 2020-08-09 21-35-35-050](https://user-images.githubusercontent.com/35269098/89735371-4e2bee80-da8c-11ea-93ab-f0d21f9fb369.jpg)
![bandicam 2020-08-09 21-37-00-755](https://user-images.githubusercontent.com/35269098/89735377-51bf7580-da8c-11ea-8ca7-41b1e8caf889.jpg)
![bandicam 2020-08-09 21-37-33-753](https://user-images.githubusercontent.com/35269098/89735379-5421cf80-da8c-11ea-9d83-af5ef6247d30.jpg)

**Comment by EmulationFanatic** [comment] 2020-08-09 15:05
Closed as duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/306

**Closed by EmulationFanatic** 2020-08-09 15:05 UTC
