### ISSUE TITLE
AJ : AAT 3D Crash

### ISSUE THREAD

**Issue by AKHELOsa** [Ryujinx/Ryujinx-Games-List#4908] opened 2024-03-24 00:53 UTC
### Game Name

Apollo Justice : Ace Attorney Trilogy

### Game Update Version

1.0.1

### Emulator Build Version

1.1.0+cc62400

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Crash when 3D animation appear

### Screenshots

https://github.com/Ryujinx/Ryujinx-Games-List/assets/164700184/faa7374c-5a24-427c-a1b2-dcd194df96cf

### Log File

00:00:00.044 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.051 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.051 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.051 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.052 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.053 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.053 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2188
00:00:00.054 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.055 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.055 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.056 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.061 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.061 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.061 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.061 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.062 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.062 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.063 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.063 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.063 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.063 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.065 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.068 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.0+cc62400
00:00:00.072 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.072 |N| Application Print: CPU: AMD Ryzen 7 5800X 8-Core Processor ; 16 logical
00:00:00.073 |N| Application Print: RAM: Total 31.9 GiB ; Available 23.8 GiB
00:00:00.075 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.075 |N| Application PrintSystemInfo: Launch Mode: UserProfile

**Comment by AKHELOsa** [comment] 2024-03-24 00:58
Ryujinx just force closed when 3D animation appeared

**Comment by piplup55** [comment] 2024-03-24 11:35
duplicate of #4862

**Closed by piplup55** 2024-03-24 11:35 UTC
