### ISSUE TITLE
Ori and the Will of the Wisps

### ISSUE THREAD

**Issue by kfreed12** [Ryujinx/Ryujinx-Games-List#4426] opened 2023-02-14 07:05 UTC
### Game Name

Ori and the Will of the Wisps

### Game Update Version

1.1.0

### Emulator Build Version

1.1.0-macos1

### Graphics Backend

Vulkan

### Hardware Specs

Tested on a 14" MacBook Pro and an M2 Air

- ##### CPU: Apple M1 Pro / M2
- ##### GPU:  Apple M1 Pro / M2
- ##### RAM: 16 on both systems

### Game State

Ori and the Will of the Wisps stutters like crazy. Framerate drops into the 10s and 20s more than it is at playable frame rates. Please let me know if I can help with any further information.

**Comment by GamerzHell9137** [comment] 2023-02-14 11:32
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2781

**Comment by AcK77** [comment] 2023-02-14 11:51
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/2781

(You can post your feedback there if you want to)

**Closed by AcK77** 2023-02-14 11:51 UTC
