### ISSUE TITLE
Musou OROCHI 3 - 0100E8500AD58000

### ISSUE THREAD

**Issue by jb522185660** [Ryujinx/Ryujinx-Games-List#5024] opened 2024-08-06 10:01 UTC
### Game Name

Musou OROCHI 3

### Game Update Version

0100E8500AD58000

### Emulator Build Version

1.1.1372

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Apple M3
- ##### GPU: Apple M3
- ##### GPU Driver version: Apple M3
- ##### RAM: 24GB

### Game State

Crash when upon entering battle

### Screenshots

![WeChat39d3dc4a71566e0285c3d458ce49fafe](https://github.com/user-attachments/assets/6c497fe7-9a90-4a73-9813-6de27e8595d0)

### Log File

[Ryujinx_1.1.1372_2024-08-06_18-00-39.log](https://github.com/user-attachments/files/16508727/Ryujinx_1.1.1372_2024-08-06_18-00-39.log)

**Comment by piplup55** [comment] 2024-08-06 16:26
duplicate of #1051

**Closed by piplup55** 2024-08-06 16:26 UTC
