### ISSUE TITLE
Pikmin 4's Visuals are Broken on AMD

### ISSUE THREAD

**Issue by ReporterNotCoder** [Ryujinx/Ryujinx-Games-List#4664] opened 2023-06-30 02:16 UTC
### Game Name

Pikmin 4 Demo

### Game Update Version

1.0

### Emulator Build Version

1.1.942

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU:  Ryzen 5 3600
- ##### GPU: RX 580 8gb
- ##### GPU Driver: 23.5.2
- ##### RAM: 2 * 8GB

### Game State

Gameplay runs well, it's just the visuals that are completely broken. Cutscenes are stuttering and lightning is all over the place during gameplay. 

### Screenshots

https://github.com/Ryujinx/Ryujinx-Games-List/assets/138178907/4a75a6cb-66a2-443a-a7d0-be2b14029352

https://github.com/Ryujinx/Ryujinx-Games-List/assets/138178907/2cf529ed-6488-47bf-8df4-01780bf24eca

https://github.com/Ryujinx/Ryujinx-Games-List/assets/138178907/72ee5afd-c8c8-41e6-88af-1ea4750ca5e6

https://github.com/Ryujinx/Ryujinx-Games-List/assets/138178907/1d014932-cf4e-437a-ba53-72315db23fd7

### Log File

[Ryujinx_1.1.942_2023-06-29_22-05-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11911969/Ryujinx_1.1.942_2023-06-29_22-05-54.log)
[Ryujinx_1.1.942_2023-06-29_22-24-34.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11911971/Ryujinx_1.1.942_2023-06-29_22-24-34.log)

**Comment by MetrosexualGarbodor** [comment] 2023-06-30 02:21
Duplicate of #4662

**Closed by MetrosexualGarbodor** 2023-06-30 02:21 UTC
