### ISSUE TITLE
Xenoblade Chronicles 2, cloud glitches

### ISSUE THREAD

**Issue by oilbugxx** [Ryujinx/Ryujinx-Games-List#4764] opened 2023-10-14 08:37 UTC
### Game Name

Xenoblade Chronicles 2

### Game Update Version

2.1.0

### Emulator Build Version

1.1.1052

### Graphics Backend

OpenGL

### Hardware Specs

CPU: Ryzen 5 5600g
GPU: Vega 7 (iGPU)
RAM: 16GB

### Game State

the game runs well for a few minutes a tested it. but you will immidiately encounter this issue from the very beginning in game intro. the cloud always glitching atleast for the times i playtested it, which is not very far from the intro battle. i know this is an issue as well on the other emulator, but i dont think i saw someone mention this issue here yet. 

i saw a video of steamdeck emulating this as well on other emulator, having similar issue. so, i guess it mostly happens on amd apu then. 

### Screenshots

![ryujinx_capture_2023-10-14_15-32-59](https://github.com/Ryujinx/Ryujinx-Games-List/assets/128238827/a084622c-d920-464f-ac6d-4f902006ed29)
![ryujinx_capture_2023-10-14_15-33-25](https://github.com/Ryujinx/Ryujinx-Games-List/assets/128238827/321c9f9b-2828-42d1-b39d-0a4a7538517c)
![ryujinx_capture_2023-10-14_15-33-36](https://github.com/Ryujinx/Ryujinx-Games-List/assets/128238827/89f48a95-9ba8-4bd0-9f4f-7f37494cdd3e)
![ryujinx_capture_2023-10-14_15-33-57](https://github.com/Ryujinx/Ryujinx-Games-List/assets/128238827/05099008-5b91-4b7b-bded-0cf5705dbc77)

**Comment by MetrosexualGarbodor** [comment] 2023-10-14 12:44
Duplicate of #159

**Closed by MetrosexualGarbodor** 2023-10-14 12:44 UTC
