### ISSUE TITLE
Kirby and the Forgotten Land - 01004D300C5AE000

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx-Games-List#3873] opened 2022-03-30 10:53 UTC
#### Current on `master` : Commit Id *or* Build Version : 1.1.85

Game runs fine with some graphical glitches. Some people are reporting crashes but haven't had them myself.

Invalid texture format is spammed in the console log but doesn't stop the gameplay

```
00:12:31.897 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x7FFFF (sRGB: False).
```

#### Outstanding Issues:

```
1. Textboxes are randomly corrupted and show a broken texture. Same with Soda count, hints that show your abilities etc.
2. Textboxes might flicker sometimes
3. Ice effect of the ice power up is broken in some places
4. Sometimes text overlaps itself
6. Rails textures are broken in certain places
7. Scanning amiibos makes the game stutter, lose FPS and renders pretty much unplayable. Issue 3241 on Ryujinx/Ryujinx
```

https://user-images.githubusercontent.com/2002038/156602788-b096a4e1-7d54-416a-acb2-5ee91484df37.mp4

https://user-images.githubusercontent.com/2002038/156605426-ae513379-ac61-4812-9a11-ec05b7fc7201.mp4

https://user-images.githubusercontent.com/2002038/156609721-04782872-5b65-4dea-b14b-75857ccaeaf2.mp4

![image](https://user-images.githubusercontent.com/2002038/160812809-790fbc78-3307-490a-bd09-1ac4c5562d75.png)
![image](https://user-images.githubusercontent.com/2002038/160812836-f4fe808c-9622-45e7-b946-f16089acc2f2.png)

#### Screenshots :

![image](https://user-images.githubusercontent.com/2002038/160814805-db52de7f-647d-41cb-a8f4-ea0b4d59f2da.png)

![image](https://user-images.githubusercontent.com/2002038/160814936-0cdc44e2-d4da-4c33-a6e5-d3c21c3b4b8f.png)

![image](https://user-images.githubusercontent.com/2002038/160815026-698436a2-b2b2-422e-8eaf-31bfd04c8440.png)

**Comment by MutantAura** [comment] 2022-03-30 18:29
Duplicate of #3866

**Closed by MutantAura** 2022-03-30 18:29 UTC
Labels: gpu, status-ingame

**Comment by ManNguyen1997** [comment] 2022-04-01 17:20
how to download??
