### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by jasonargoargo** [Ryujinx/Ryujinx-Games-List#5058] opened 2024-09-11 04:18 UTC
### Game Name

Disgaea 7: Vows of the Virtueless

### Game Update Version

1.0.5

### Emulator Build Version

18.0.0

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Game crashed when loading battle 4-1. Upon reload, game was able to load battle 4-1. Not sure what caused the initial crash. 

### Log File

00:00:00.056 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.056 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.063 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.064 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.064 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.187 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.188 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.190 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.196 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.196 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.196 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.196 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.197 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.197 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.198 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.198 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.198 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.198 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.198 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.198 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.199 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.199 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.202 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.202 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.202 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.202 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.203 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.368 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1359
00:00:00.372 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.372 |N| Application Print: CPU: AMD Ryzen 5 7530U with Radeon Graphics ; 12 logical
00:00:00.374 |N| Application Print: RAM: Total 7.3 GiB ; Available 0.8 GiB
00:00:00.376 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.377 |N| Application PrintSystemInfo: Launch Mode: Portable

**Comment by ekuland** [comment] 2024-09-11 13:02
Incomplete template, empty log, possibly a dupe of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4425 , although it may be a different language.

**Closed by ekuland** 2024-09-11 13:02 UTC
