### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by imadethisaccountsoicanmakeanissue** [Ryujinx/Ryujinx-Games-List#3665] opened 2021-07-23 01:36 UTC
#### Game Update Version : 3.0.1

Playable, 3D World not so much.

##### RAM: 16GB

My Issue is that,

![image](https://user-images.githubusercontent.com/75588579/126728158-e62b02f0-8795-4ef3-83a0-45365a2618cb.png)

**Comment by AcK77** [comment] 2021-07-23 02:03
Duplicate of #180

**Closed by AcK77** 2021-07-23 02:03 UTC

**Comment by imadethisaccountsoicanmakeanissue** [comment] 2021-07-23 02:16
how is that related

**Comment by AcK77** [comment] 2021-07-23 02:17
I suggest you to read https://github.com/Ryujinx/Ryujinx-Games-List/blob/master/README.md

**Comment by imadethisaccountsoicanmakeanissue** [comment] 2021-11-01 23:55
this is status-ingame not status-working

**Comment by MutantAura** [comment] 2021-11-02 15:31
Read the link above. One issue per game, if you have further comments to add then add them to that issue.
We don't have multiple pages for the same game.
