### ISSUE TITLE
Catherine: Full Body eu version 

### ISSUE THREAD

**Issue by sinou666** [Ryujinx/Ryujinx-Games-List#3283] opened 2021-01-30 23:51 UTC
## Game Name

Game Update Version : 1.0.1/ eur

Current on master : 1.0.6455
for my part the games launch well, the textures are good, but after a while the games crash and I have a frozen screen why ? .. 

Hardware Specs :
GPU : GTX 970 4gb
CPU :ryzen 2600
RAM : KINGSTON DDR4 16GB

00:00:19.772 |S| HLE.OsThread.9 ServiceHid IsVibrationPermitted: Stubbed. {_vibrationPermitted: False}
00:00:19.791 |I| HLE.OsThread.5 ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:00:20.270 |I| HLE.GuestThread.18 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
sdk:0x001824a0 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
sdk:0x00182564 Sub000000000cead564
sdk:0x00182600 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
sdk:0x003399c8 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
sdk:0x00331638 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
main:0x002fd860 Sub0000000008301860
sdk:0x003344b8 Sub000000000d05f4b8
sdk:0x00338984 Sub000000000d063984
??? Sub0000000000000000

00:00:20.272 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:20.272 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:20.272 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:20.272 |W| HLE.GuestThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.

**Comment by EmulationFanatic** [comment] 2021-01-31 00:09
Please post game tests as replies to existing issues!
Closing as duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3232

**Closed by EmulationFanatic** 2021-01-31 00:09 UTC
Labels: duplicate
