### ISSUE TITLE
Mario Party Superstars v1.1.1 [01006fe013472000]

### ISSUE THREAD

**Issue by avidichard** [Ryujinx/Ryujinx-Games-List#4211] opened 2022-11-15 21:59 UTC
Mario Party Superstars
v1.1.1
Ryujinx v1.1.344
Graphics: Vulkan

When wanting to select a profile on the number of players select screen, if you select the "Guest" option below the player to choose a profile for that player, Ryujinx shuts down with no error screen or warning.

```
Last error returned:

00:00:18.824 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
```

Hardware Specs : 

CPU: AMD Ryzen 5 3600
GPU: Zotac NVidia GTX 980 Ti AMP! Extreme 6 gb
RAM: 16 Gb

Screenshots :

![Player Profile Select Screen](https://i.imgur.com/7WGQSK8l.png)

Log file :

[Ryujinx_1.1.343_2022-11-14_17-32-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10016462/Ryujinx_1.1.343_2022-11-14_17-32-00.log)

**Comment by othmanead** [comment] 2022-11-15 22:01
this is duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3752

**Comment by MetrosexualGarbodor** [comment] 2022-11-15 22:11
Please post this in #3752. Thank you.

**Closed by MetrosexualGarbodor** 2022-11-15 22:11 UTC
