### ISSUE TITLE
Baldo The guardian owls - 0100A75005E92000

### ISSUE THREAD

**Issue by Rolbag** [Ryujinx/Ryujinx-Games-List#4235] opened 2022-11-26 19:49 UTC
##### RAM: *16GB*

Game crashes randomly. On startup, after some seconds, some minutes*

```
Last error returned.
Game crash after loading the world
```

#### Log file:

*[Ryujinx_1.1.390_2022-11-26_20-41-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10096930/Ryujinx_1.1.390_2022-11-26_20-41-43.log)*

**Comment by EmulationFanatic** [comment] 2022-11-26 20:09
Closing as duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4165

**Closed by EmulationFanatic** 2022-11-26 20:09 UTC
Labels: Incomplete
