### ISSUE TITLE
Civilization 6 [010044500c182000] map does not render after entering the game

### ISSUE THREAD

**Issue by cnmmg** [Ryujinx/Ryujinx-Games-List#4900] opened 2024-03-17 03:58 UTC
### Game Name

Civilization 6

### Game Update Version

v1114112 and later

### Emulator Build Version

1.1.1231

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(m3 max)*
- ##### GPU: *(m3 max)*
- ##### GPU Driver version: *(m3 max)*
- ##### RAM: *(36GB)*

### Game State

The overall rendering effect is very weird

### Screenshots

<img width="1453" alt="截屏2024-03-17 11 57 24" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/130685213/85850c78-204a-4a9a-a0db-500dfe72bc00">

**Comment by piplup55** [comment] 2024-03-17 07:33
duplicate of #1491

**Closed by piplup55** 2024-03-17 07:33 UTC
