### ISSUE TITLE
Nier AUTOMATA progress in stability and graphic quality with few drops in fps but it closes / Crashing before the first boss and does not allow saving, how do I skip that boss or reduce the possibility of crash

### ISSUE THREAD

**Issue by Warwolf127** [Ryujinx/Ryujinx-Games-List#4974] opened 2024-05-25 00:19 UTC
### Game Name

Nier Automata 

### Game Update Version

1.0.2

### Emulator Build Version

Ryujinx  1.1.1321

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *(. i7-9300H)*
- ##### GPU: *(. NVIDIA GTX 2060)*
- ##### GPU Driver version: *( 555.85)*
- ##### RAM: *(dual channel  16GB)*

### Game State

Since the last update Nier automata runs well until the first boss, few frame drops after knocking out the crane and 9s falls on it when going up the circular ramp it collapses, my theory is that the cpu is loaded a lot I must clarify that my team has an nvidia 2060 and core i79300H and 16 ram in win 11, I remain attentive and greatly appreciate the progress in my favorite game, I clarify that it ran in the Dock at 1080p without overscaling and an anisotropic in 2x in Vulkan Automatic mode

### Screenshots

![445174710_10233756808768955_366678138911012001_n](https://github.com/Ryujinx/Ryujinx-Games-List/assets/170709120/f85f5289-469c-40e0-932a-7aa4803fab8c)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/170709120/7f0b9ed9-e704-4146-8afe-ba4d9dc0cbb0)

### Log File

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/170709120/6636a1d6-d002-49a1-9c4e-49fe8dd16be3)

**Comment by piplup55** [comment] 2024-05-25 01:13
duplicate of #4067

**Closed by piplup55** 2024-05-25 01:13 UTC
