### ISSUE TITLE
New Super Mario Bros. U Deluxe - 0100EA80032EA000

### ISSUE THREAD

**Issue by xionfr40** [Ryujinx/Ryujinx-Games-List#4386] opened 2023-01-25 14:20 UTC
### Game Name

New Super Mario Bros. U Deluxe - [0100EA80032EA000]

### Game Update Version

1.0.0

### Emulator Build Version

1.1.595

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Core i7 1265U
- ##### GPU: Intel(R) Iris(R) Xe Graphics / drivers 31.0.101.4032 / 12/21/2022
- ##### RAM: 16GB

### Game State

Game is playable well until this level: Jungle Cassis
![1](https://user-images.githubusercontent.com/36473102/214587143-7a2ec27a-8be0-47de-a159-081729fc7776.PNG)

After a screen animation is played (to go to the castle), Games hang

![2](https://user-images.githubusercontent.com/36473102/214587111-f71697df-eb25-4401-a0f4-be392c8a4f04.PNG)

Here is the error:

00:01:09.344 |D| SurfaceFlinger.Composer SurfaceFlinger AcquireBuffer: Max acquired buffer count reached: 2 (max: 1)
00:01:09.361 |D| SurfaceFlinger.Composer SurfaceFlinger AcquireBuffer: Max acquired buffer count reached: 2 (max: 1)
00:01:09.368 |D| HLE.OsThread.10 ServiceNv PrintResult: SubmitGpfifoEx returned result Success
00:01:09.368 |D| HLE.OsThread.10 ServiceNv PrintResult: SubmitGpfifoEx returned result Success
00:01:09.394 |D| SurfaceFlinger.Composer SurfaceFlinger AcquireBuffer: Max acquired buffer count reached: 2 (max: 1)
00:01:09.410 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 315
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 202
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\Window.cs:line 257
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 115
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 400

### Log File

[Ryujinx_1.1.595_2023-01-25_13-50-04 - Copie.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10500154/Ryujinx_1.1.595_2023-01-25_13-50-04.-.Copie.log)

**Comment by MetrosexualGarbodor** [comment] 2023-01-25 20:59
Duplicate of #1137

**Closed by MetrosexualGarbodor** 2023-01-25 20:59 UTC
