### ISSUE TITLE
hanz

### ISSUE THREAD

**Issue by thewodioftime** [Ryujinx/Ryujinx-Games-List#4906] opened 2024-03-21 09:14 UTC
### Game Name

The Legend of Zelda: Tears of the Kingdom

### Game Update Version

1.1.0

### Emulator Build Version

1.1.799

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

df

### Screenshots

dfd

### Log File

efd

**Comment by piplup55** [comment] 2024-03-21 12:18
duplicate of #4598

**Closed by piplup55** 2024-03-21 12:18 UTC
