### ISSUE TITLE
Pokémon Scarlet crashing my system 

### ISSUE THREAD

**Issue by KiwiInFlight** [Ryujinx/Ryujinx-Games-List#4259] opened 2022-12-04 07:30 UTC
##### RAM: 16GB
Ventura 13.0.1

Game crashes OS
I can choose my name and my look and accept then after the music changes it freezes until my Mac restarts itself

**Comment by MetrosexualGarbodor** [comment] 2022-12-04 14:10
A crash report is useless without logs. Closing as duplicate of #4218.

**Closed** 2022-12-04 14:09 UTC
