### ISSUE TITLE
Nights of Azure 2 crash at special attack tuto

### ISSUE THREAD

**Issue by Linteckh** [Ryujinx/Ryujinx-Games-List#4767] opened 2023-10-14 19:06 UTC
### Game Name

Nights of Azure 2: Bride of the New Moon

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1052

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i7-9700K
- ##### GPU: RTX 3090Ti
- ##### RAM: 48GB 3200Mhz

### Game State

Game is running fine 'till it freeze than crash when you get to the point where you learn the special attack (in the tutorial) while smashing the A button in the first city

### Screenshots

As said the game run fine until it just crash, so i don't have screenshot rn

### Log File

Ain't got any log file in the "Logs" subfolder even if the "Logging to File" checkbox is set on

**Comment by MetrosexualGarbodor** [comment] 2023-10-14 19:08
Duplicate of #84

**Closed by MetrosexualGarbodor** 2023-10-14 19:08 UTC

**Comment by Linteckh** [comment] 2023-10-14 19:12
It's not the same bug and the other one have not been updated since 2022 so I didn't know if I had to write it in the other issue, sorry o/

**Comment by gdkchan** [comment] 2023-10-14 19:16
Attach a save and instructions to reproduce the issue.

**Comment by Linteckh** [comment] 2023-10-14 19:23
The game don't have time to autosave and you can't save manually this early in the game so the save folder is empty, to reproduce you just need to launch a new game, play utile you get the pop-up to press A to activate the special attack, then when it say to smash the A button it will freeze with the controller still rumbling and then crash. There is no error or any red line in the cmd box so I can't see if it's the shader compilation that crash the game has I already had with other game in the past or else (tried deleting all cache files and shader to see but it didn't do anything)

**Comment by gdkchan** [comment] 2023-10-14 19:59
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/5624669/b1c171b7-e873-44ff-8a7d-cca0ae90501f)
Can't reproduce the issue here, I played until after where you create the save file (chapter 1).
Also got past the part of the tutorial where it asks you to keep pressing A.
It would be useful to have a log, I'm not sure why it's not creating the log file for you. Are you checking the correct logs folder?

**Comment by Linteckh** [comment] 2023-10-14 20:04
Mmmmmh, maybe it's the 1.0.1 update, or the 16.1.0 firmware. Ima retry as soon as I can without the update and else to see, and on a fresh Ryujinx folder to see if it works or if I can get a log file. Yep I'm opening it through directly. I'll come back with more detail asap. Thx !

**Comment by Linteckh** [comment] 2023-10-14 21:02
Okay so, without the 1.0.1 update the game crash when launching a new game like the other post, with nothing in the log like it didn't crash. With the 1.0.1 update but without any DLC the games works fine. And with 1.0.1 plus the dlc it was only mentioned "ErrorOutOfDeviceMemory" (forgot to save the file before the other test) even if my monitoring was showing I had still 28GB free of RAM, 20GB free of VRAM and 31GB free of virtual memory. So I'm kinda lost tbh. But at least the game works great without dlc !
![PrtScr capture](https://github.com/Ryujinx/Ryujinx-Games-List/assets/18294383/23e7af25-c621-4ae7-963c-0c7b3c120d3d)
![PrtScr capture_2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/18294383/44b0bddd-7772-44de-a937-10a611e01a3e)
