### ISSUE TITLE
Pokemon enable

### ISSUE THREAD

**Issue by Tansino** [Ryujinx/Ryujinx-Games-List#4951] opened 2024-05-01 21:46 UTC
### Game Name

Pokemon

### Game Update Version

1.3.2

### Emulator Build Version

1.1.1296

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Pokemon game Ryujinx

**Comment by ekuland** [comment] 2024-05-01 21:50
Not even partially completed. I assume a duplicate of either https://github.com/Ryujinx/Ryujinx-Games-List/issues/232 or https://github.com/Ryujinx/Ryujinx-Games-List/issues/4035 based on version alone.

**Closed** 2024-05-01 21:51 UTC
