### ISSUE TITLE
Pokemon Sword 

### ISSUE THREAD

**Issue by legendaryghi** [Ryujinx/Ryujinx-Games-List#3427] opened 2021-03-07 19:59 UTC
Pokemon Sword

#### Current on `Ryukinx` : ver. 1.0.6776

status-ingame , slow , bugs , crashing from time-to-time
```
I've been playing this a month ago, i do enjoy this game but is seems it's one of the slow working game where on outside map i get between 12-18 fps, meanwhile in battles or inside of houses i get a nice decent 24-30 fps, always when i play a new move i never used before it lags and the fps drop to 2-4 fps but after that no problem. i have seen some visual bugs, where pokemons were not rendered correctly but after the updates i was going trough it stoped.
Only bug i've noticed and it's pretty annoying it's when i try to play a mini-game called Watts Digging it needs to save, but at that save everything stops beside the sound, the sound goes on. I've attached some pictures for more details!

#### Hardware Specs : 

##### CPU: i5-9300H
##### GPU: NVidia GeForce GTX 1650
##### RAM: 8GB RAM
##### OS: Windows 10 Pro 

![3](https://user-images.githubusercontent.com/80221150/110252905-54d20400-7f90-11eb-9a8d-4ccc28e2f90f.jpg)
![1](https://user-images.githubusercontent.com/80221150/110252909-56033100-7f90-11eb-8966-179aafd681cd.jpg)
![2](https://user-images.githubusercontent.com/80221150/110252910-56033100-7f90-11eb-81e5-5eddbc52442d.jpg)

**Comment by EmulationFanatic** [comment] 2021-03-07 20:02
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/232
Please use the LDN build for the best performance in this game currently.

**Closed by EmulationFanatic** 2021-03-07 20:02 UTC
Labels: duplicate
