### ISSUE TITLE
Pokemon Sword : random crash

### ISSUE THREAD

**Issue by dunboss** [Ryujinx/Ryujinx-Games-List#4291] opened 2022-12-14 19:58 UTC
#### Graphics Backend: *Vulkan*

Hello, the other day i had a random crash while playing Pokemon Sword. I was chaining panchams and Ryujinx closed (right when i was out of pp 😭 ). It's the second time it happened and i'm afraid i could lose more that random encounters in the future

[Ryujinx_1.1.468_2022-12-12_21-30-02.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10231211/Ryujinx_1.1.468_2022-12-12_21-30-02.log)

**Comment by EmulationFanatic** [comment] 2022-12-14 20:00
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/232

**Closed by EmulationFanatic** 2022-12-14 20:00 UTC
