### ISSUE TITLE
Paper Mario crashes on launch

### ISSUE THREAD

**Issue by Drenatheon** [Ryujinx/Ryujinx-Games-List#5007] opened 2024-07-03 21:37 UTC
### Game Name

Paper Mario: The Thousand-Year Door

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1340 

### Graphics Backend

Vulkan

### Hardware Specs

- CPU: AMD Ryzen 5 5600
- GPU: AMD RX6600
- GPU Driver version: 24.6.1
- RAM: 16GB

### Game State

if i try to launch the game it crashes instantly after the nintendo logo, i already tried different settings and nsp and xci version. In addition i also tried the pptc fix without success.

### Log File

[Ryujinx_1.1.1340_2024-07-03_23-35-12.log](https://github.com/user-attachments/files/16090995/Ryujinx_1.1.1340_2024-07-03_23-35-12.log)

**Comment by piplup55** [comment] 2024-07-04 02:40
duplicate of #4972

**Closed by piplup55** 2024-07-04 02:40 UTC
