### ISSUE TITLE
Cadence of Hyrule Vulkan Performance Issues

### ISSUE THREAD

**Issue by 4ng3l33t** [Ryujinx/Ryujinx-Games-List#4294] opened 2022-12-18 02:35 UTC
##### RAM: 32GB

Played the game for about 1 hour.  In the Deku Village in the time warp/dark world area the GPU usage pegs at 99% according to task manager and the FPS drops to about 20-30.  In the nearby areas FPS struggles to stay at 40.  OpenGL Backend has 60FPS, but similar GPU usage.
#### Screenshots:

![image](https://user-images.githubusercontent.com/120869625/208278576-ab59769d-5752-407a-a3c1-6694f84fcc79.png)

![image](https://user-images.githubusercontent.com/120869625/208278605-f808fdf5-2a51-44ba-a282-161cd7371038.png)

#### Log file:

*Add a log file here. 
Can be found in the logs folder, in the same directory as the Ryujinx executable, or through File > Open logs folder.*

[Ryujinx_1.1.476_2022-12-17_21-25-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10253097/Ryujinx_1.1.476_2022-12-17_21-25-49.log)

**Comment by MetrosexualGarbodor** [comment] 2022-12-18 02:55
Duplicate of #200

**Closed by MetrosexualGarbodor** 2022-12-18 02:55 UTC
