### ISSUE TITLE
勇敢和贪婪- [0100F60017D4E000]无法开始

### ISSUE THREAD

**Issue by LIIIhao** [Ryujinx/Ryujinx-Games-List#4843] opened 2023-12-19 02:59 UTC
### Game Name

Bravery and Greed

### Game Update Version

v1.0

### Emulator Build Version

1.1.1100

### Graphics Backend

Vulkan

### Hardware Specs

Mac  M1 16G

### Game State

Bravery and Greed cannot start

### Log File

[Uploading Ryujinx_1.1.1100_2023-12-19_10-50-07.log…]()

**Comment by OldManKain** [comment] 2023-12-19 03:20
Duplicate of #4257

**Closed by OldManKain** 2023-12-19 03:20 UTC
