### ISSUE TITLE
Pokemon Scarlet issue: Light blue lines/blue fog

### ISSUE THREAD

**Issue by Demonsflame592** [Ryujinx/Ryujinx-Games-List#5037] opened 2024-08-17 03:09 UTC
### Game Name

Pokemon Scarlet 

### Game Update Version

3.0.1

### Emulator Build Version

1.1.1375

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: 3.6 GHz Quad-Core Intel Core i3
- ##### GPU: AMD Radeon Pro 555X (dGPU)
- ##### GPU Driver version: Sonoma 14.6.1
- ##### RAM: *(e.g. 16GB)*
![IMG_0744](https://github.com/user-attachments/assets/0058bacc-70a9-4cef-9124-5f81193fdb29)
![IMG_0741](https://github.com/user-attachments/assets/e791353c-05f8-40d7-91be-bf95adfaba03)

### Game State

None

### Log File

[Ryujinx_1.1.1375_2024-08-16_19-46-53.log](https://github.com/user-attachments/files/16643213/Ryujinx_1.1.1375_2024-08-16_19-46-53.log)

**Comment by piplup55** [comment] 2024-08-17 16:21
duplicate of #4218

**Closed by piplup55** 2024-08-17 16:21 UTC
