### ISSUE TITLE
New Pokemon Snap Crashing at the end of the courses

### ISSUE THREAD

**Issue by Maklem1989** [Ryujinx/Ryujinx-Games-List#3687] opened 2021-08-27 22:32 UTC
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

*Describe the current game state here. Crashing

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

##### RAM: *(e.g. 8GB)*

The game is working weel, but when the course ends, the emulator closes and crash. It happens in every course.

**Comment by gdkchan** [comment] 2021-08-30 07:21
Duplicate of #3669.

**Closed by gdkchan** 2021-08-30 07:21 UTC
