### ISSUE TITLE
Disgaea 5 Complete 01005700031AE000

### ISSUE THREAD

**Issue by HaiLung** [Ryujinx/Ryujinx-Games-List#4677] opened 2023-07-07 14:52 UTC
### Game Name

Disgaea 5 Complete

### Game Update Version

1.0.0 and 1.0.4

### Emulator Build Version

1.1.955

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- i5-8400
- NVIDIA  GTX 1060
- RAM: 16 GB

### Game State

Some cutscenes that are  crashing but skippable, but the cutscene at the end of the mission "Dreaming Mushroom" in Episode 4 is unskippable and crashes the game.
 After crashing and trying to open the game at the title screen it crashes again duo to that cutscene trying to play again.

[Save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11982992/Save.zip)

The broken but Skippable cutscenes before Episode 4 are
-Red Magnus Super Joins the Team (Eposode 1)
-Rebel Army Organized (Episode 2)
-Killia Vs. Zeroken (Episode 3)

### Log File

[Ryujinx_1.1.955_2023-07-07_16-05-25.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11982956/Ryujinx_1.1.955_2023-07-07_16-05-25.log) "Dreaming Mushroom" log

[Ryujinx_1.1.955_2023-07-07_16-42-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11983148/Ryujinx_1.1.955_2023-07-07_16-42-21.log) "Killia Vs. Zeroken" log

[Ryujinx_1.1.955_2023-07-07_16-44-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11983169/Ryujinx_1.1.955_2023-07-07_16-44-45.log) "Red Magnus Super Joins the Team" log

[Ryujinx_1.1.955_2023-07-07_16-47-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11983180/Ryujinx_1.1.955_2023-07-07_16-47-28.log) "Rebel Army Organized" log

**Comment by MutantAura** [comment] 2023-07-08 15:53
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/472
Please post updates to the above.

**Closed by MutantAura** 2023-07-08 15:53 UTC
