### ISSUE TITLE
Ben 10 Power trip 01009CD00E3AA000

### ISSUE THREAD

**Issue by deepeshgamer** [Ryujinx/Ryujinx-Games-List#3620] opened 2021-06-01 09:48 UTC
Ben 10 power trip

Game version - 1.0.0

Master build - 1.0.6894

Having a graphic issue at loading the screen also having audio issue when loading audio repeat 2-3 times when loading !! Most of time seeing sturring and get softlock at somelocation

Hardware Specs : 

CPU: i5-2390T
GPU: NVIDIA 710 
Ram : 14 GB

![Screenshot (2)](https://user-images.githubusercontent.com/66416897/120303306-58a1c800-c2ec-11eb-9845-10c861f09306.png)

#![Screenshot (4)](https://user-images.githubusercontent.com/66416897/120303324-5ccde580-c2ec-11eb-885a-2d9c6b539421.png)

My log file - 
[Ryujinx_1.0.6894_2021-06-01_14-54-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6575248/Ryujinx_1.0.6894_2021-06-01_14-54-00.log)

**Comment by EmulationFanatic** [comment] 2021-06-01 11:23
Closing as duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/2871. Please post game tests on the original post.

**Closed by EmulationFanatic** 2021-06-01 11:23 UTC
Labels: duplicate
