### ISSUE TITLE
Pokémon Scarlet - 0100A3D008C5C000 #4218 

### ISSUE THREAD

**Issue by uzumaki-kira** [Ryujinx/Ryujinx-Games-List#4270] opened 2022-12-06 01:47 UTC
Pokémon Scarlet - 0100A3D008C5C000 #4218 

Windows 10
Ryujinx 1.1.430
Vulkan

Hardware Specs: 
CPU: Ryzen 5 5600x
GPU: RTX 2080 super
RAM: 32gb 3600mhz

The state of the game is definitely playable and runs with higher resolution and 16x anistropic filtering. However there are some areas with stutter and slowdowns, especially the area at the top right corner of the map with the tall trees and fallen leaves, where the fps momentarily drops to 20s. Other than that, the game is very much playable with very minor graphical bugs and no game breaking issues have been experienced on this emulator and it plays just like the native switch version except with higher resolution depending on how powerful the rig is.

Screenshots:

![image](https://user-images.githubusercontent.com/119906267/205786313-af7e348e-7a4b-4296-9e9c-5f9889a2913c.png)

![image](https://user-images.githubusercontent.com/119906267/205786495-186073da-7568-4c5a-a0e6-4145cd9129e7.png)

![image](https://user-images.githubusercontent.com/119906267/205787107-5b2667db-2c4b-4598-912e-44de171f8083.png)

![image](https://user-images.githubusercontent.com/119906267/205787350-15960fd4-63fc-4a87-960c-131abfa8f3f2.png)

![image](https://user-images.githubusercontent.com/119906267/205787784-cb084d6f-8116-4caf-a0a9-36824090e223.png)

**Comment by MetrosexualGarbodor** [comment] 2022-12-06 01:51
Duplicate of #4218

**Closed by MetrosexualGarbodor** 2022-12-06 01:51 UTC
