### ISSUE TITLE
 "the match was terminated".

### ISSUE THREAD

**Issue by lilxluuc** [Ryujinx/Ryujinx-Games-List#4720] opened 2023-08-17 01:49 UTC
### Game Name

Mario Strikers Battle League

### Game Update Version

1.0.0

### Emulator Build Version

Ryujinx 1.1.0-ldn 3.1.3

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i5-7600k
- ##### GPU: NVIDIA GTX 1070 TI
- ##### RAM: 16GB

### Game State

I tried playing with a friend. it worked at first until the match started, then we got a message "the match was terminated". that happened in our both attempts. does anybody know what's the issue?

**Comment by MutantAura** [comment] 2023-08-19 15:07
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3910

**Closed by MutantAura** 2023-08-19 15:07 UTC
