### ISSUE TITLE
Pikmin 4 Compatibility Report

### ISSUE THREAD

**Issue by ImpartyPlays** [Ryujinx/Ryujinx-Games-List#4695] opened 2023-07-24 07:12 UTC
### Game Name

Pikmin 4

### Game Update Version

1.0.1

### Emulator Build Version

1.1.968

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Intel Core i5-10400F
- ##### GPU: Nivida Geforce RTX 3060
- ##### RAM: 16 Gbs

### Game State

title screen and credits studders a lot 
it suddenly drops to 0 fps randomly but comes back in ~5 seconds
map has graphical problems

**Comment by Jkosio23** [comment] 2023-07-25 13:37
With openGL i've noticed that the shader that deals with time of day flickers between all sorts of colors

**Comment by MutantAura** [comment] 2023-07-31 17:44
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4693

**Closed by MutantAura** 2023-07-31 17:44 UTC
