### ISSUE TITLE
Grandia HD - Crashes at the initial stage of startup

### ISSUE THREAD

**Issue by psychokinesis9** [Ryujinx/Ryujinx-Games-List#4621] opened 2023-05-19 18:39 UTC
### Game Name

Grandia HD

### Game Update Version

1.01.19

### Emulator Build Version

1.1.807

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: CPU: Intel Corei7-1255U / AMD Ryzen 5 3600
- ##### GPU: Intel Intel Iris(R) Xe Graphics / RTX 2060 SUPER
- ##### RAM: 16GB / 32GB

### Game State

Crashes immediately after game startup, before the publisher logo appears.
If the game with no updates(v1.00), it starts correctly
However, when I updated the game to v1.01.19, getting crashes immediately on all CPUs, GPUs and Graphics APIs.

The error code is always the same.

>  Log level: Info
>    Time: 8s
>    ProgramName: Grandia_Main_Boot
>    Thread: MainThread
>    Filename: E:/Projects/Grandia/GrandiaLauncher/Grandia_Main_Boot/switch_Movie.cpp
>    Line: 423
>    Function: Update
>    Message: _videoDecoder->GetOutputBuffer() failed: Status_ErrorTimeOut
>
>00:00:09.497 |S| HLE.OsThread.22 ServiceMm SetAndWait: Stubbed. {id: 1 ; frequenceHz: 3875766000 ; timeout: -1}
>00:00:09.509 |I| HLE.OsThread.22 ServiceAm SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001)).

### Screenshots

None

### Log File

[Ryujinx_1.1.807_2023-05-20_03-22-52.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11519569/Ryujinx_1.1.807_2023-05-20_03-22-52.log)

**Comment by MetrosexualGarbodor** [comment] 2023-05-19 18:42
Duplicate of #1681

**Closed by MetrosexualGarbodor** 2023-05-19 18:42 UTC
