### ISSUE TITLE
Splatoon 2 Crash after tutorial

### ISSUE THREAD

**Issue by BrknGmr** [Ryujinx/Ryujinx-Games-List#3761] opened 2021-11-04 17:58 UTC
#### Current on `master` : Commit Id *or* Build Version : 1.0.7096
Game crashes after tutorial. Importing a save file doesn't change much, crashes after a few minutes in the main hub. 

```
Last error returned.
e.g.: Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
```

#### Log file :

[Ryujinx_1.0.7096_2021-11-03_22-35-11.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7477160/Ryujinx_1.0.7096_2021-11-03_22-35-11.log)

**Comment by gdkchan** [comment] 2021-11-04 18:01
Duplicate of #703, and this is a controller issue, you need to make sure player 2 controller (or any other controller that is not player 1) is disabled.

**Closed by gdkchan** 2021-11-04 18:01 UTC

**Comment by Abdul8910** [comment] 2023-07-09 14:21
> Duplicate of #703, and this is a controller issue, you need to make sure player 2 controller (or any other controller that is not player 1) is disabled.

I checked that all the other controllers were disabled, and it still crashes after tutorial.
I use a 2020 MacBook Air M1

**Comment by Kucchan67346** [comment] 2023-07-29 01:20
My Mac also has the crashing issue on the loading screen after the tutorial.
I use a MacBook Pro 2023 M2 Pro model. 
Looking at other users' reports, this is mostly a problem with Macs with his M1 or newer CPUs, and it's still not resolved.

**Comment by Kucchan67346** [comment] 2023-07-29 01:32
Resolved by applying the latest release of Ryujinx.
https://github.com/Ryujinx/release-channel-master/releases

**Comment by Kucchan67346** [comment] 2023-07-29 01:33
You should download the last version of Ryujinx manually here : 
https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.969
