### ISSUE TITLE
MLB® The Show™ 22

### ISSUE THREAD

**Issue by lucter0218** [Ryujinx/Ryujinx-Games-List#4371] opened 2023-01-20 09:41 UTC
### Game Name

MLB® The Show™ 22

### Game Update Version

1.0.13

### Emulator Build Version

1.1.575

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: i5-8500
- ##### GPU: GTX 1060 6GB
- ##### RAM: DDR4 16GB

### Game State

everyone looks black like screenshot (I am not English speaker so I cannot write anymore)

### Screenshots

![에러](https://user-images.githubusercontent.com/123132529/213663329-3f44b44c-fc43-4d0c-b8f9-56680079df88.png)

**Comment by GamerzHell9137** [comment] 2023-01-20 09:42
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3875

**Comment by MutantAura** [comment] 2023-01-20 10:28
Duplicate of #3875 
Please leave your comment there instead.

**Closed by MutantAura** 2023-01-20 10:28 UTC
