### ISSUE TITLE
GTA San Andreas - Definitive Edition

### ISSUE THREAD

**Issue by RyanTheGamerIlGuerri** [Ryujinx/Ryujinx-Games-List#4932] opened 2024-04-15 16:35 UTC
### Game Name

GTA San Andreas Definitive Edition

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1111

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

I open it and everything is ok. Simply when I click "Play" what happens is the following screen (shown below in the image) and the emulator crashes

### Screenshots
![Proofs](https://github.com/Ryujinx/Ryujinx-Games-List/assets/167116819/d5bf297a-070b-4a9e-9478-cc6d39d953d7)

_No response_

**Comment by RyanTheGamerIlGuerri** [comment] 2024-04-15 16:35
![Uploading Proofs.jpg…]()

**Comment by piplup55** [comment] 2024-04-15 17:38
duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4156

**Closed by piplup55** 2024-04-15 17:38 UTC
