### ISSUE TITLE
mario vs donkey kong

### ISSUE THREAD

**Issue by Siljo1** [Ryujinx/Ryujinx-Games-List#4923] opened 2024-04-04 02:42 UTC
### Game Name

mario vs donkey kong

### Game Update Version

1.01

### Emulator Build Version

1.1.1250

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Does Not load,crashes completely on start.
Version 1.0 works

**Comment by piplup55** [comment] 2024-04-04 15:58
duplicate of #4871

**Closed by piplup55** 2024-04-04 15:58 UTC
