### ISSUE TITLE
The Legend of Zelda Tears of the Kingdom 

### ISSUE THREAD

**Issue by tipoddreh** [Ryujinx/Ryujinx-Games-List#4606] opened 2023-05-13 19:08 UTC
### Game Name

The Legend of Zelda Tears of the Kingdom 

### Game Update Version

1.1.0

### Emulator Build Version

1.1.0 macOS build 

### Graphics Backend

Vulkan

### Hardware Specs

Mac M1 Pro 

### Game State

the game is playable at stable 30 fps (with the 30 fps mod) but. noticed lots of random crashes.

**Comment by MetrosexualGarbodor** [comment] 2023-05-13 20:00
Duplicate of #4598

**Closed by MetrosexualGarbodor** 2023-05-13 20:00 UTC
