### ISSUE TITLE
MLB The Show 24 - 0100E2E01C32E000

### ISSUE THREAD

**Issue by tw94015** [Ryujinx/Ryujinx-Games-List#4976] opened 2024-05-27 11:52 UTC
### Game Name

MLB The Show 24

### Game Update Version

1.0.8

### Emulator Build Version

1.1.1325

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *(R5 7500F)*
- ##### GPU: *(e.g. NVIDIA RTX 4060Ti)*
- ##### GPU Driver version: *(e.g. 555.85)*
- ##### RAM: *(e.g. 32GB)*

### Game State

MLB The Show 24 runs smoothly using OpenGL, but player eyes cannot be rendered. I also tried running it with Vulkan, but it crashes every time I enter a game. This is a shame and I hope Vulkan support for MLB The Show will be fixed as soon as possible.

### Log File

[Ryujinx_1.1.1325_2024-05-27_13-26-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15455473/Ryujinx_1.1.1325_2024-05-27_13-26-30.log)

**Comment by mrmos** [comment] 2024-05-31 08:00
I was able to get around the crash by enabling the setting: 

Options > Settings > System > hacks > Ignore missing services

**Comment by tw94015** [comment] 2024-05-31 15:31
I have enabled it, but the game still crashes when I enter a match.

**Comment by Pr0lixCoding** [comment] 2024-05-31 22:09
Are you on Windows? On Fedora 40, the emulator crashes when trying to pick teams. Nvidia 2070 super with 555.42.02 drivers and ryzen 7 3700x. Doesn't matter if it's openGL or vulkan.

**Comment by MetrosexualGarbodor** [comment] 2024-07-19 03:04
Duplicate of #4896

**Closed by MetrosexualGarbodor** 2024-07-19 03:04 UTC
