### ISSUE TITLE
SaGa Frontier Remastered v1.0.3 Don't Work

### ISSUE THREAD

**Issue by momoids** [Ryujinx/Ryujinx-Games-List#3648] opened 2021-07-11 03:05 UTC
SaGa Frontier Remastered

Game Update Version : v1.0.3

Current on master : 1.0.6959

Game don't boot for me!

Hardware Specs : 

 CPU: Ryzen 1600x
GPU: Nvidia GTX 1060 6GB
RAM: 32GB

Log file :
[Ryujinx_1.0.6959_2021-07-10_23-51-22.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6796291/Ryujinx_1.0.6959_2021-07-10_23-51-22.log)

**Comment by AcK77** [comment] 2021-07-11 08:59
Duplicate of #3550

**Closed by AcK77** 2021-07-11 08:59 UTC
