### ISSUE TITLE
mofumofusensen - 0100B46017500000

### ISSUE THREAD

**Issue by drewtig** [Ryujinx/Ryujinx-Games-List#4885] opened 2024-03-08 19:40 UTC
### Game Name

mofumofusensen

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1221

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *i7-8086K*
- ##### GPU: *AMD Radeon RX 6650 XT*
- ##### GPU Driver version: *23.40.19.01-240215a1-400566C-AMD-Software-Adrenalin-Edition*
- ##### RAM: *32GB*

### Game State

Game will launch and sound can be heard (music / sound effects).  Graphics are black screen with a full-screen light flash (part of the game intro).  Controls are responsive - pressing start twice will get to a menu, moving up/down on d-pad results in menu sounds.

### Log File

[Ryujinx_1.1.1221_2024-03-08_11-34-09.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14542468/Ryujinx_1.1.1221_2024-03-08_11-34-09.log)

**Comment by MutantAura** [comment] 2024-03-09 01:20
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3913

**Closed by MutantAura** 2024-03-09 01:20 UTC
