### ISSUE TITLE
MORTAL KOMBAT 11 40 FPS and shadows glitched

### ISSUE THREAD

**Issue by xlsami503** [Ryujinx/Ryujinx-Games-List#4609] opened 2023-05-15 02:29 UTC
### Game Name

Mortal Kombat 11 [0100F2200C984000][v0]

### Game Update Version

Mortal Kombat 11 [0100F2200C984800][v1114112][Aftermath]

### Emulator Build Version

1.1.800

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. Ryzen 5 3400g)*
- ##### GPU: *(e.g. APU)*
- ##### RAM: *(e.g. Dual Channel 16GB RAM3200 Mhz)*

### Game State

I trying to play Mortal Kombat 11 in ryujinx, but it runs at 40 FPS, and I was looking that someone had the same issue as me, and he solved it, but I don't know how he did that. And the FPS are not the only issue, there's some shadows in terms of graphics that are glitched or bugged.

**Comment by MetrosexualGarbodor** [comment] 2023-05-15 02:30
Duplicate of #165

**Closed by MetrosexualGarbodor** 2023-05-15 02:30 UTC
