### ISSUE TITLE
Freezing after like 3-5 mins into gameplay

### ISSUE THREAD

**Issue by fesho265** [Ryujinx/Ryujinx-Games-List#5053] opened 2024-09-05 08:54 UTC
### Game Name

Sonic Frontiers

### Game Update Version

1.4.1

### Emulator Build Version

1.1.1385-win_x64

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *(i5-12500H)*
- ##### GPU: *(NVIDIA RTX 3050Ti)*
- ##### GPU Driver version: *(560.94)*
- ##### RAM: *(16 GB)*

### Game State

Game runs just fine at stable 30fps with no graphical errors at all, until you're like 3-5 mins into gameplay then freezes.
Sometimes it freezes with music still running.
I can tweak in settings, like upscaling graphics or lowering it, it still runs at 30fps also, but still freezes.
the screenshot added below is out of the cyberspace, but the issue happens in cyberspace too.

### Screenshots

![Screenshot (425)](https://github.com/user-attachments/assets/fd909a22-1917-4861-b47a-279342d1c57a)

### Log File

[Ryujinx_1.1.1385_2024-09-05_11-32-38.log](https://github.com/user-attachments/files/16886617/Ryujinx_1.1.1385_2024-09-05_11-32-38.log)

**Comment by piplup55** [comment] 2024-09-05 08:59
Duplicate of #4174

**Closed by piplup55** 2024-09-05 08:59 UTC
