### ISSUE TITLE
Spelunky 2- [01007EC013ABC000]无法启动

### ISSUE THREAD

**Issue by LIIIhao** [Ryujinx/Ryujinx-Games-List#4841] opened 2023-12-19 02:51 UTC
### Game Name

Spelunky 2

### Game Update Version

v1.28

### Emulator Build Version

1.1.1100

### Graphics Backend

Vulkan

### Hardware Specs

Mac M1 16G

### Game State

cannot start

### Log File

[Uploading Ryujinx_1.1.1100_2023-12-19_10-50-07.log…]()

**Comment by OldManKain** [comment] 2023-12-19 03:19
Duplicate of #3774

**Closed by OldManKain** 2023-12-19 03:19 UTC
