### ISSUE TITLE
Manticore - Galaxy on Fire - 0100C9A00952A000

### ISSUE THREAD

**Issue by SamuelGlushkin** [Ryujinx/Ryujinx-Games-List#3667] opened 2021-07-28 09:30 UTC
#### Ryujinx version: 1.0.6976

*Does not get past intro screen into the menu.*

```
No errors returned, just stuck on a black screen near 10.76 FPS. The game shows the dev logo and then stays on a black screen. Ryujinx crashes if an attempt to shut the game down is made.
```

#### Screenshot:
![image](https://user-images.githubusercontent.com/60011444/127297405-7e065477-35e8-43e4-8e34-ae14dd6ccfc7.png)

#### Log file :
https://pastebin.com/4zzW0hBz

**Comment by EmulationFanatic** [comment] 2022-08-03 21:54
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/603

**Closed by EmulationFanatic** 2022-08-03 21:54 UTC
Labels: status-boots
