### ISSUE TITLE
METAL MAX Xeno Reborn

### ISSUE THREAD

**Issue by Catiks** [Ryujinx/Ryujinx-Games-List#3226] opened 2020-12-31 08:57 UTC
METAL MAX Xeno Reborn
Game Update Version : 1.0.0
Current on master : 1.0.6182
The game is slow and there is a problem, the character will teleport when walking. And the graphics are slightly damaged and flashing as the game running, And the the FPS is become very low.

Hardware Specs : 

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
GPU: Intel Corporation UHD Graphics 630 (Desktop 9 Series) (rev 02)
 RAM: 32GB

**Comment by EmulationFanatic** [comment] 2020-12-31 10:24
Intel UHD 630 graphics are not a supported platform. Please re-test the game with an AMD or NVIDIA GPU.

**Comment by Cronos-0** [comment] 2020-12-31 14:03
@Catiks duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/2681

**Comment by EmulationFanatic** [comment] 2020-12-31 14:04
Closing as duplicate

**Closed by EmulationFanatic** 2020-12-31 14:04 UTC
Labels: duplicate
