### ISSUE TITLE
Worms W.M.D - 01001AE005166000

### ISSUE THREAD

**Issue by earl80** [Ryujinx/Ryujinx-Games-List#3884] opened 2022-04-24 06:30 UTC
Worms W.M.D

Game Version : 1.0.0

Current on `master` : 1.1.106

with the new Ryujnix Version are the interlaced look history. The Game loads and plays with high FPS and without grafic Issues, but with no Worms...

Last error returned.
e.g.: GPU.MainThread Gpu UpdateVertexAttribState: Invalid attribute format 0x25E00000.

Hardware Specs : 

CPU: 12600K
GPU: RTX3060
RAM: 32GB

#### Screenshots :

![ryujinx_capture_2022-04-24_08-14-47](https://user-images.githubusercontent.com/103452942/164959634-949a08ef-23b8-4a39-8345-84a68d8e3a8b.png)
![ryujinx_capture_2022-04-24_08-24-27](https://user-images.githubusercontent.com/103452942/164959701-f314d7ef-1b71-4744-9e03-11d6686890a9.png)

**Comment by MetrosexualGarbodor** [comment] 2022-04-24 23:02
Duplicate of #358. Please post this as a comment there.

**Closed by MetrosexualGarbodor** 2022-04-24 23:02 UTC
