### ISSUE TITLE
Xenoblade Chronicles 2 framerate

### ISSUE THREAD

**Issue by cloudzack83** [Ryujinx/Ryujinx-Games-List#3640] opened 2021-06-30 22:42 UTC
Xenoblade Chronicles 2

2.0.2

The Game works fine but the framerate is very slow in many parts of the game, is there a way to improve it? Thanks

##### RAM: 16GB

![XC 2-1](https://user-images.githubusercontent.com/85825655/124040375-1bbd1400-da05-11eb-8fec-965b2a56f140.jpg)
![XC 2-2](https://user-images.githubusercontent.com/85825655/124040381-1f509b00-da05-11eb-9829-a7d84ec5948b.jpg)
![XC 2-3](https://user-images.githubusercontent.com/85825655/124040382-211a5e80-da05-11eb-92b1-98eb0f92ed42.jpg)
[Ryujinx_1.0.6945_2021-06-30_00-17-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6744366/Ryujinx_1.0.6945_2021-06-30_00-17-23.log)

**Comment by EmulationFanatic** [comment] 2021-07-01 19:39
Closing as duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/159

**Closed by EmulationFanatic** 2021-07-01 19:39 UTC
