### ISSUE TITLE
Super Mario Bros U Deluxe very slow game walkthrough

### ISSUE THREAD

**Issue by BeatriXis** [Ryujinx/Ryujinx-Games-List#4365] opened 2023-01-17 10:44 UTC
### Game Name

Super Mario Bros U Deluxe

### Game Update Version

1.0.0

### Emulator Build Version

Ryujinx 15.0.1

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Intel Core i5 dual-core
- ##### GPU: Intel Iris Plus Graphics 640 1536MB
- ##### RAM: 8GB

### Game State

Game starts but it is very very slow. What can be the issue? How to resolve it? Same think happens with Maria Kart 8 Deluxe. These are the first two games I'm trying with Ryujinx. Thanks 

### Screenshots

![IMG_0864](https://user-images.githubusercontent.com/122874511/212878358-4bba9142-9479-43d8-ba6e-a8c3a35da485.jpg)

### Log File

Ryujinx_ 1.1.0-macos1_2023-01-16_22-15-03.log
Ryujinx_ 1.1.0-macos1_2023-01-16_19-54-00.log
Ryujinx_ 1.1.0-macos1_2023-01-16_18-02-38.log

**Comment by EmulationFanatic** [comment] 2023-01-17 12:43
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/1137

**Closed by EmulationFanatic** 2023-01-17 12:43 UTC
