### ISSUE TITLE
eBASEBALLパワフルプロ野球2022 - 0100BCA016636000

### ISSUE THREAD

**Issue by UltraDanHR** [Ryujinx/Ryujinx-Games-List#4928] opened 2024-04-07 21:33 UTC
### Game Name

eBASEBALLパワフルプロ野球2022

### Game Update Version

1.13.1

### Emulator Build Version

1.1.1266

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: i7-7700K
- ##### GPU: NVIDIA GTX 1080
- ##### GPU Driver version: 551.76
- ##### RAM: 16GB

### Game State

Crashes. Gives the following exception:
Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Hid.IHidServer

Tried downgrading versions and removing DLCs if anything changed, but everything was the same.

### Log File

[Ryujinx_1.1.1266_2024-04-07_23-26-06.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14899041/Ryujinx_1.1.1266_2024-04-07_23-26-06.log)

**Comment by gdkchan** [comment] 2024-04-07 21:39
Duplicate of #4010. You can enable ignore missing services in the emulator settings system tab to bypass that error.

**Closed by gdkchan** 2024-04-07 21:39 UTC
