### ISSUE TITLE
The Legend of Zelda: Tears of the Kingdom

### ISSUE THREAD

**Issue by pixelatedname** [Ryujinx/Ryujinx-Games-List#4618] opened 2023-05-18 18:45 UTC
### Game Name

The Legend of Zelda: Tears of the Kingdom

### Game Update Version

1.1.0

### Emulator Build Version

1.1.804

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Custom APU 0405*
- ##### GPU: *Custom APU 0406*
- ##### RAM: *16 GB*
- ##### System: *Steam Deck*

### Game State

Game works well, stuck at 20 FPS during most gameplay. However during and after reviving Ganondorf I've noticed a 7-10 second audio lag.

**Comment by MutantAura** [comment] 2023-05-18 18:46
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598

**Closed by MutantAura** 2023-05-18 18:46 UTC

**Comment by noxifoxi** [comment] 2023-05-18 20:38
> However during and after reviving Ganondorf I've noticed a 7-10 second audio lag.

Switching to the OpenAL Audio backend on Arch Linux (Steam Deck is also Arch based) solved that for me.

**Comment by VladKih** [comment] 2024-08-15 06:57
q
