### ISSUE TITLE
in the underground, the map gives me gloom all the time, i can't walk or do something

### ISSUE THREAD

**Issue by zacrox** [Ryujinx/Ryujinx-Games-List#4612] opened 2023-05-16 02:47 UTC
### Game Name

zelda tears of the kingdom

### Game Update Version

1.1

### Emulator Build Version

1.1.800

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *AMD RYZEN 5600G*
- ##### GPU: *AMD RYZEN 5600G*
- ##### RAM: *16GB*

### Game State

when link walks in the underground he starts to take  damage like he would be under ganon's aura effect even if you don't walk over the gloom

### Screenshots

![Screenshot_1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/36437865/b66b0b5a-1bee-4e4a-8ae4-6d2c4d02bf3e)
![Screenshot_2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/36437865/68e865a3-5a8e-4f9e-8d56-b1654619dc8e)

### Log File

[Ryujinx_1.1.800_2023-05-15_19-41-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11483506/Ryujinx_1.1.800_2023-05-15_19-41-40.log)

this is the last log that i have

**Comment by MetrosexualGarbodor** [comment] 2023-05-16 02:53
Duplicate of #4598

**Closed by MetrosexualGarbodor** 2023-05-16 02:53 UTC

**Comment by Tosh0kan** [comment] 2023-05-16 17:05
@zacrox it's called invisigloom. Known issue with AMD gpus. Check https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598#issuecomment-1546721351 for fix
