### ISSUE TITLE
Yoshi's Crafted World - 010060000040C2000

### ISSUE THREAD

**Issue by randrade86** [Ryujinx/Ryujinx-Games-List#3593] opened 2021-05-16 22:35 UTC
#### Current on `master` : 1.0.6874

Playable with small FPS drops. Cannot progress in "Go-Go Yoshi" level due to a white screen. See the screenshot for more details.

#### Screenshots :
![image](https://user-images.githubusercontent.com/5365488/118414914-ba6ffa00-b67d-11eb-84ca-c5588fbd8836.png)

**Comment by EmulationFanatic** [comment] 2021-05-17 12:48
Closing as duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3561

**Closed by EmulationFanatic** 2021-05-17 12:48 UTC
Labels: duplicate
