### ISSUE TITLE
Minecraft: Story Mode - The Complete Adventure

### ISSUE THREAD

**Issue by michaelmelnic** [Ryujinx/Ryujinx-Games-List#4295] opened 2022-12-18 17:04 UTC
![SCR-20221218-gor](https://user-images.githubusercontent.com/120963024/208310321-66c6c5b0-7419-4f9e-92c0-d8112f0ec5c2.jpeg)
Minecraft: Story Mode - The Complete Adventure

game ver 1.0.0

1.1.0-macos 1

gpu Vulkan

Hardware Specs: 

##### RAM: 64g

game bootes to menu but crashes if you go any further. fix turn off vsync and try until you go further into the game the game will crash multiple times, but then one time it will succeed. You'll only have to do this once, and then it will be booting every time.
![SCR-20221218-gnn](https://user-images.githubusercontent.com/120963024/208310272-b560372a-365a-4026-b028-ae149c26bfbc.jpeg)
![SCR-20221218-gnz](https://user-images.githubusercontent.com/120963024/208310279-5c33a5db-cba7-4607-9a1c-fbc4aa747456.jpeg)
![SCR-20221218-goe](https://user-images.githubusercontent.com/120963024/208310288-64807ebb-a96b-4117-907f-dd59fc842010.jpeg)
![SCR-20221217-wqt](https://user-images.githubusercontent.com/120963024/208310295-680f5e6e-1fb5-468b-a6b6-1f606e430980.png)

```
Last error returned.
Add the last error in the log if there is any.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Screenshots:

*Add screenshots here (preferably on windowed mode) if the game is rendering.*

#### Log file:

*Add a log file here. 
Can be found in the logs folder, in the same directory as the Ryujinx executable, or through File > Open logs folder.*

**Comment by EmulationFanatic** [comment] 2022-12-18 17:16
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3969. Please post the respective information as a comment on the original entry.

**Closed by EmulationFanatic** 2022-12-18 17:16 UTC

**Comment by cddude** [comment] 2024-01-15 00:34
Tested on 1/14/24 with version 1.1.1110 and does not crash after selecting character.  Did not test further past then.
