### ISSUE TITLE
Disgaea 5 Complete

### ISSUE THREAD

**Issue by Noein198** [Ryujinx/Ryujinx-Games-List#4719] opened 2023-08-14 11:00 UTC
### Game Name

Disgaea 5 Complete

### Game Update Version

1.0.4

### Emulator Build Version

16.0.3

### Graphics Backend

Vulkan

### Hardware Specs

- Apple M2 CPU: *(e.g. i7-6700)*
- Apple M2 GPU: *(e.g. NVIDIA RTX 2070)*
- 8GB RAM: *(e.g. 16GB)*

### Game State

Some cutscenes that are crashing but skippable, but the cutscene at the end of the mission "Dreaming Mushroom" in Episode 4 is unskippable and crashes, making it impossible to complete the game. Detailed sequence:
1. At the end of mission system plays cutscene (works ok) and prompt save game (as it is the end of episode). After save it crashes.
2. Re-launching & loading save instantly crashes. 

Tried to play with various Ryujinx settings - no luck. 

Looking for solution I found similar issue which is marked as closed, but it is for PC. 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4677

### Log File

[Ryujinx_ 1.1.0-macos1_2023-08-14_12-29-20.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12333989/Ryujinx_.1.1.0-macos1_2023-08-14_12-29-20.log)
[Ryujinx_ 1.1.0-macos1_2023-08-14_12-43-57.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12333990/Ryujinx_.1.1.0-macos1_2023-08-14_12-43-57.log)
[Ryujinx_ 1.1.0-macos1_2023-08-14_12-29-20.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12333991/Ryujinx_.1.1.0-macos1_2023-08-14_12-29-20.log)

**Comment by GamerzHell9137** [comment] 2023-08-14 11:43
https://github.com/Ryujinx/Ryujinx-Games-List/issues/472

**Comment by riperiperi** [comment] 2023-08-17 12:13
You should check if this issue runs with hypervisor disabled in the options.

**Comment by Noein198** [comment] 2023-08-17 12:58
Zipped entire .../user/save folder as I'm not sure which file exactly is save. Let me know if need anything else. Thank you for your time. 
[save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/12369529/save.zip)

**Comment by MutantAura** [comment] 2023-08-19 15:06
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/472.
Can you please shift this into a comment on that report.

**Closed by MutantAura** 2023-08-19 15:06 UTC
