### ISSUE TITLE
play The Legend of Zelda: Breath of the Wild  ryujinx crash

### ISSUE THREAD

**Issue by newengineer123** [Ryujinx/Ryujinx-Games-List#4364] opened 2023-01-17 09:14 UTC
### Game Name

The Legend of Zelda: Breath of the Wild

### Game Update Version

1.6

### Emulator Build Version

test-ava-ryujinx-1.1.550-win_x64--test-ava-ryujinx-1.1.569-win_x64

### Graphics Backend

Vulkan

### Hardware Specs

i7-6700K   NVIDIA GTX 970  16GB

### Game State

雪原打人马的时候打到一半进行报错后程序崩溃，程序直接退出，无法截图
When Xueyuan hits a horse halfway through the error, the program crashes, and the program exits directly, unable to take screenshots

00:01:13.597 |E| HLE.GuestThread.19 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000001673A7000.
00:01:13.683 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()

00:03:44.547 |E| HLE.GuestThread.19 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000021687E1000.
00:03:44.626 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()

00:04:33.509 |E| HLE.GuestThread.19 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x000000216B2AE000.
00:04:33.557 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270

### Screenshots

When Xueyuan hits a horse halfway through the error, the program crashes, and the program exits directly, unable to take screenshots

### Log File

00:00:00.053 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.057 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.058 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.058 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.059 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.060 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.060 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x13C2
00:00:00.062 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.063 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.063 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.063 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.063 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.063 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.063 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.063 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.063 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.064 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.064 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.064 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.064 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.070 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.559
00:00:00.074 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.074 |N| Application Print: CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz ; 8 logical
00:00:00.075 |N| Application Print: RAM: Total 16326 MiB ; Available 8381 MiB
00:00:00.078 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.078 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.151 |I| Gpu : Backend Threading (On): True
00:00:00.407 |N| Application LoadGuestApplication: Using Firmware Version: 15.0.1
00:00:00.407 |I| Application LoadGuestApplication: Loading as XCI.
00:00:00.463 |I| Application AddAocItem: Found AddOnContent with TitleId 01007EF00011F002
00:00:00.463 |I| Application AddAocItem: Found AddOnContent with TitleId 01007EF00011F001
00:00:00.481 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.482 |I| ModLoader QueryTitleDir: Found mod '60FPS' [E]
00:00:00.482 |I| ModLoader QueryTitleDir: Found mod 'Disable Dynamic Resolution' [E]
00:00:00.483 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001
00:00:00.483 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002
00:00:00.483 |I| ModLoader QueryContentsDir: Searching mods for Title 01007EF00011E000
00:00:00.483 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F001
00:00:00.483 |I| ModLoader QueryContentsDir: Searching mods for DLC 01007EF00011F002
00:00:00.486 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.492 |I| Loader LoadExeFs: Loading rtld...
00:00:00.499 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.499 |I| Loader LoadExeFs: Loading main...
00:00:00.810 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Cafe\U-King\trunk\Game\App\Rom\NX64\Product\code\U-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_G3d-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-4_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_libcurl-4_4_0-Release
                   SDK MW+Nintendo+NEX-4_2_1-ALZ
                   SDK MW+Nintendo+NEX_DS-4_2_1
                   SDK MW+Nintendo+NEX_UT-4_2_1
                   SDK MW+Nintendo+NintendoSDK_gfx-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Font-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-4_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Atk-4_4_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2014_2
                   SDK MW+Microsoft+Havok-2014_2
                   SDK MW+Microsoft+Havok_Physics2012-2014_2
                   SDK MW+Microsoft+Havok_AI-2014_2
                   SDK MW+Microsoft+Havok_Animation-2014_2
00:00:00.810 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.857 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-4_4_0-Release
00:00:00.857 |I| Loader LoadExeFs: Loading sdk...
00:00:00.925 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 4.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-4_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-4_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-4_4_0-Release
00:00:01.073 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.102 |I| Ptc Load: Loaded Translation Cache (size: 87819208 bytes, translated functions: 81989).
00:00:02.126 |I| Ptc Load: Loaded Profiling Info (size: 291019 bytes, profiled functions: 81989).
00:00:02.135 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.137 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.148 |I| Loader LoadNsos: Loading image 2 at 0x000000000a6af000...
00:00:02.150 |I| Loader LoadNsos: Loading image 3 at 0x000000000ad95000...
00:00:02.156 |I| ModLoader LoadCheats: Build ids found for title 01007EF00011E000:
    D33817C0C763D8FAF97D9A6534C19DB231FF7271000000000000000000000000
    16A91992BBA71201E98756F3BC8F5D2F00000000000000000000000000000000
    D9DE423EFC1512328C3C05378C7CB03173FACDE3000000000000000000000000
    BA520906609C503227871A314A94FB5F6CCBE444000000000000000000000000
00:00:02.156 |I| Loader LoadNca: Application Loaded: The Legend of Zelda: Breath of the Wild v1.5.0 [01007ef00011e000] [64-bit]
00:00:02.224 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.240 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.477 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 970 (Vulkan v1.2.175, Driver v472.12.0.0)
00:00:02.486 |I| GPU.MainThread Gpu LoadShaders: Loading 2067 shaders from the cache...
00:00:24.104 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:24.999 |I| HLE.GuestThread.19 Ptc LoadTranslations: 81989 translated functions loaded
00:00:25.125 |S| HLE.OsThread.20 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:25.129 |S| HLE.OsThread.20 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:25.129 |S| HLE.OsThread.20 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:25.130 |S| HLE.OsThread.20 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:25.139 |S| HLE.OsThread.20 ServicePctl Initialize: Stubbed. 
00:00:26.324 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 26s
    Thread: MainThread
    Filename: D:/home/Cafe/U-King/trunk/Game/Lib/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp
    Line: 18
    Function: PrintStringImpl
    Message: 0000002d

00:00:26.325 |S| HLE.OsThread.20 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:26.326 |S| HLE.OsThread.20 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:26.326 |S| HLE.OsThread.20 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:26.391 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:26.397 |I| HLE.OsThread.20 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:26.417 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:26.432 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:26.478 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:26.479 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:26.479 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:26.480 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:26.481 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:26.481 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:26.482 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:00:26.483 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:26.504 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 0}
00:00:26.509 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:26.509 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 96 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:26.513 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:26.544 |S| HLE.OsThread.20 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72197163296350208}
00:00:26.583 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:26.594 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007EF00011F001
00:00:26.605 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:26.607 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=01007EF00011F001
00:00:27.773 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:27.774 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:31.445 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:31.448 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV4
00:00:31.467 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:31.468 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:31.487 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:31.564 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:31.703 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceSystemEvent: Stubbed. 
00:00:31.704 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:31.752 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 96 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:34.238 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:34.665 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; _gyroscopeZeroDriftMode: Tight}
00:00:46.578 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 96
 UserId: 00000000000000010000000000000000
 Room: option 
 Report: {
    "BalloonTextOnOff": 1,
    "AutoSaveOnOff": 1,
    "CameraUpDownReverse": 0,
    "CameraRLReverse": 0,
    "TextRubyOnOff": 1,
    "JumpButtonChange": 1,
    "StickSensitivity": 3,
    "GyroOnOff": 1,
    "MiniMapDirection": 1,
    "AmiiboItemOnOff": 0,
    "MainScreenOnOff": 0,
    "TextWindowChange": 1,
    "DockInOnOff": 1,
    "ControllerType": 1,
    "AttachExtGrip": 0,
    "CtrlModeHandheldFree": 0,
    "CtrlModeHandheldExt": 0,
    "CtrlModeHandheldFullKey": 213958,
    "CtrlModeHandheldHandheld": 0,
    "CtrlModeConsoleFree": 0,
    "CtrlModeConsoleExt": 0,
    "CtrlModeConsoleFull": 117109,
    "PlayTimeHandheld": 213958,
    "PlayTimeConsole": 117109,
    "PlayTimeAll": 331067,
    "RomVer": 150,
    "AoCVer": 30,
    "RegionLanguage": 226,
    "AudioMono": 0,
    "AudioStereo": 282142,
    "Audio5_1ch": 48925,
    "AudioOther": 0
}

00:01:13.594 |I| HLE.GuestThread.19 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 96
   0x0000000009611798	main:0x160d798	
   0x00000000096396b8	main:0x16356b8	
   0x000000000962b7e8	main:0x16277e8	
   0x0000000009612488	main:0x160e488	
   0x000000000958895c	main:0x158495c	
   0x00000000092b7f8c	main:0x12b3f8c	
   0x000000000921a370	main:0x1216370	
   0x0000000008f423c4	main:0xf3e3c4	
   0x00000000087b2248	main:0x7ae248	
   0x00000000087d5ed0	main:0x7d1ed0	
   0x00000000087cbaa4	main:0x7c7aa4	
   0x0000000008aff190	main:0xafb190	
   0x0000000008aff1a8	main:0xafb1a8	
   0x0000000008aff1a8	main:0xafb1a8	
   0x0000000008aff1a8	main:0xafb1a8	
   0x0000000008aff148	main:0xafb148	
   0x0000000008dcec9c	main:0xdcac9c	
   0x0000000008dcea5c	main:0xdcaa5c	
   0x0000000008afe5fc	main:0xafa5fc	
   0x00000000087da3a8	main:0x7d63a8	nnMain:0x03c4
   0x000000000ae03dfc	sdk:0x6edfc	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()):0x004c
   0x00000000080000ac	rtld:0x00ac	

00:01:13.597 |I| HLE.GuestThread.19 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x00000001673a7be0
	X[01]:	0x000000118bb025a0 (SP:-0x0030)
	X[02]:	0x000000118bb025e8 (SP:-0x0078)
	X[03]:	0x000000118bb026d0 (SP:-0x0160)
	X[04]:	0x0000000000000007
	X[05]:	0x0000000000000150
	X[06]:	0x0000000000000008
	X[07]:	0x000000000000001c
	X[08]:	0xffffffffbf6e294c
	X[09]:	0x00000000bf6e294d
	X[10]:	0x0000000009f05d0c
	X[11]:	0x0000000000004000
	X[12]:	0x0000000000008000
	X[13]:	0x00000010ab4a69d0
	X[14]:	0x0000000000000000
	X[15]:	0x0000001011460bcc
	X[16]:	0x000000000a57ba28
	X[17]:	0x000000000ae256d0 (sdk:0x906d0)	=> nn::os::GetTlsValue(nn::os::TlsSlot)
	X[18]:	0x000000003f800000
	X[19]:	0x000000118bb028d0 (SP:-0x0360)
	X[20]:	0x00000010b7c3c940
	X[21]:	0x0000000009da7478
	X[22]:	0x00000001673a7bd0
	X[23]:	0x0000001010a8dd40
	X[24]:	0x0000000033333333
	X[25]:	0x0000000000000002
	X[26]:	0x000000000a6766b0
	X[27]:	0x0000001010a83258
	X[28]:	0x00000010b7c3c940
	FP:	0x000000118bb025f0 (SP:-0x0080)
	LR:	0x0000000009598388 (main:0x1594388)	=> 
	SP:	0x000000118bb02570 (SP)
	PC:	0x000000000958f8f4 (main:0x158b8f4)	=> 

00:01:13.597 |E| HLE.GuestThread.19 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000001673A7000.
00:01:13.683 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()

**Comment by EmulationFanatic** [comment] 2023-01-17 12:42
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/86

**Closed by EmulationFanatic** 2023-01-17 12:42 UTC

**Comment by newengineer123** [comment] 2023-01-17 16:31
what this issue casus
