### ISSUE TITLE
Super Mario Bros. Wonder - 010015100B514000

### ISSUE THREAD

**Issue by Zer0PXL** [Ryujinx/Ryujinx-Games-List#4780] opened 2023-10-21 17:11 UTC
### Game Name

Super Mario Bros. Wonder

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1059

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Intel Core i5-11400
- ##### GPU: AMD RX 6500 XT
- ##### RAM: 8 GB

### Game State

There don't seem to be any errors after 2 hours of gameplay. The game works flawlessly with 0 lag and surprisingly no stutters (for shaders).

### Screenshots

![Screenshot 2023-10-21 200321](https://github.com/Ryujinx/Ryujinx-Games-List/assets/84981290/8739b023-5b6d-4bd0-b897-9230fc4fd4c2)
![Screenshot 2023-10-21 200647](https://github.com/Ryujinx/Ryujinx-Games-List/assets/84981290/da60d924-25e4-4571-ac48-1c226a883fc6)

### Log File

[Ryujinx_1.1.1059_2023-10-21_20-02-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13061346/Ryujinx_1.1.1059_2023-10-21_20-02-12.log)

**Comment by OldManKain** [comment] 2023-10-21 18:05
Duplicate of #4776

**Closed by OldManKain** 2023-10-21 18:05 UTC

**Comment by OscarDev90** [comment] 2024-08-24 15:22
![imagen_2024-08-24_171947627](https://github.com/user-attachments/assets/b39893c2-1b96-4db3-916f-e9257296df65)
This happens when I upload my super mario wonder nsp file to ryujinx using the load application from file option

**Comment by OldManKain** [comment] 2024-08-24 15:23
I am so sick of getting emails for everything that happens on Ryujinx github, remember you guys banned me fix this shit.
