### ISSUE TITLE
The character's body graphics are not displayed.

### ISSUE THREAD

**Issue by sangshil** [Ryujinx/Ryujinx-Games-List#5017] opened 2024-07-22 23:31 UTC
### Game Name

ebaseball 2024-2025

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1359

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: m1 pro
- ##### GPU: m1 pro
- ##### GPU Driver version: 
- ##### RAM: 16GB

### Game State

The character's body graphics are not displayed.

### Screenshots

<img width="789" alt="스크린샷 2024-07-23 오전 8 20 39" src="https://github.com/user-attachments/assets/058888e6-5b32-4a42-be51-bd4a9f5a208d">

### Log File

[Ryujinx_1.1.1359_2024-07-23_08-19-06.log](https://github.com/user-attachments/files/16340635/Ryujinx_1.1.1359_2024-07-23_08-19-06.log)
[Ryujinx_1.1.1359_2024-07-23_08-20-58.log](https://github.com/user-attachments/files/16340636/Ryujinx_1.1.1359_2024-07-23_08-20-58.log)

**Comment by MetrosexualGarbodor** [comment] 2024-07-22 23:36
Duplicate of #5016

**Closed by MetrosexualGarbodor** 2024-07-22 23:36 UTC
