### ISSUE TITLE
MK8D: Crashes during loading a race and loading the cinematic before menu.

### ISSUE THREAD

**Issue by papri-ka** [Ryujinx/Ryujinx-Games-List#4532] opened 2023-03-30 15:24 UTC
### Game Name

Mario Kart 8 Deluxe

### Game Update Version

1.0.0 ; 1.7.2 ; 2.3.0. No DLC.

### Emulator Build Version

Ryujinx 1.1.0-macos1 (also tried with an own build version using the latest commits of the git repo)

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Intel Core i5-8500*
- ##### GPU: *Radeon Pro 560X 4Go*
- ##### RAM: *8 GB*
- ##### OS: *macOS Ventura 13.3*

### Game State

Game launch normally at 60FPS. 
1. If we wait ~30s and the menu's cinematic starts loading, Ryujinx crashes 
2. If we select "Grand Prix", Ryujinx crashes during the loading screen before the starting of the race.

Same happens in all the modes of the game except Battle Balloon, for what i tested.
Purging shaders/PTC doesn't change anything.

### Log File

[Ryujinx_.1.1.0-macos1_2023-03-30_17-21-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11114276/Ryujinx_.1.1.0-macos1_2023-03-30_17-21-29.log)
[Ryujinx_.1.1.0-macos1_2023-03-30_17-18-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11114277/Ryujinx_.1.1.0-macos1_2023-03-30_17-18-55.log)

**Comment by MetrosexualGarbodor** [comment] 2023-04-01 16:04
Duplicate of #244

**Closed** 2023-04-01 16:05 UTC
