### ISSUE TITLE
Change language doesn't work in Harukana Toki no Naka de 7

### ISSUE THREAD

**Issue by Rosabis** [Ryujinx/Ryujinx-Games-List#4596] opened 2023-05-09 11:20 UTC
### Game Name

Harukana Toki no Naka de 7

### Game Update Version

1.0.0

### Emulator Build Version

1.1.773

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*i7-4500u
- ##### GPU: *(e.g. NVIDIA RTX 2070)*R5 M330
- ##### RAM: *(e.g. 16GB)*8GB

### Game State

Change language doesn't work in Harukana Toki no Naka de 7
1.Change system region to Chinese
2.Change system language to Chinese
3. The game still show Japanese,instead of Chinese.

### Screenshots

![ryujinx_capture_2023-05-09_19-18-48](https://github.com/Ryujinx/Ryujinx-Games-List/assets/124857271/cefba2d2-5ca7-4701-ab91-823beccdd49a)

### Log File

[Ryujinx_1.1.742_2023-05-09_19-16-27.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11430584/Ryujinx_1.1.742_2023-05-09_19-16-27.log)

**Comment by MetrosexualGarbodor** [comment] 2023-05-09 13:36
Duplicate of #2631

**Closed by MetrosexualGarbodor** 2023-05-09 13:36 UTC
