### ISSUE TITLE
Bayonetta Origins Cereza and the Lost Demon Issue

### ISSUE THREAD

**Issue by jwxa** [Ryujinx/Ryujinx-Games-List#4678] opened 2023-07-09 08:14 UTC
### Game Name

Bayonetta Origins Cereza and the Lost Demon

### Game Update Version

1.0.0

### Emulator Build Version

1.1.9.51

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i7-9700kf
- ##### GPU: NVIDIA RTX 3080
- ##### RAM: 32GB

### Game State

when boss fight start , i can see scene
my save data is here
[0.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11994708/0.zip)

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/9533487/e63d3873-3ad1-4d62-bb2e-12dec2ba8ef3)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/9533487/6b46c017-9f23-4944-9190-ad82c88b4567)

### Log File

[Ryujinx_1.1.951_2023-07-09_16-09-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11994712/Ryujinx_1.1.951_2023-07-09_16-09-58.log)

**Comment by MetrosexualGarbodor** [comment] 2023-07-09 15:03
Duplicate of #4503

**Closed by MetrosexualGarbodor** 2023-07-09 15:03 UTC
