### ISSUE TITLE
FC 24 does not load, log files of the issue.

### ISSUE THREAD

**Issue by Andresmzayala** [Ryujinx/Ryujinx-Games-List#4754] opened 2023-09-29 15:59 UTC
### Game Name

FC 24

### Game Update Version

1.53

### Emulator Build Version

1.1.1035

### Graphics Backend

Vulkan

### Hardware Specs

MacBook Air M1 2020 256Gb

CPU: Apple M1
GPU: Apple M1
Ram: 8Gb

### Game State

The game starts until the intro then is  a loop in the animation of the loading screen it never loads.

I try with 2 firmwares:
System version 16.03 and 16.1.0 both with the same outcome.

### Screenshots

<img width="1086" alt="Screenshot 2023-09-29 at 10 55 26" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/55825703/61ec4bf3-e774-4625-9099-d924a3d74d76">

### Log File

[Ryujinx_1.1.1035_2023-09-29_10-49-41.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12768604/Ryujinx_1.1.1035_2023-09-29_10-49-41.log)

**Comment by MutantAura** [comment] 2023-09-29 16:00
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4753

**Closed by MutantAura** 2023-09-29 16:00 UTC
