### ISSUE TITLE
Divinity Original Sin 2 Definitive Edition - 010027400CDC6000

### ISSUE THREAD

**Issue by SaintZeroZ** [Ryujinx/Ryujinx-Games-List#3843] opened 2022-02-24 09:53 UTC
#### Current on `master` : Commit Id *or* Build Version : 1.1.53

*Describe the current game state here.*

When I go to story. single player and then pick classic it shows the loading screen with an empty bar and then crashes.

#### Log file :

[Ryujinx_1.1.53_2022-02-24_04-42-37.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8131454/Ryujinx_1.1.53_2022-02-24_04-42-37.log)

**Comment by MetrosexualGarbodor** [comment] 2022-02-24 12:07
Duplicate of #1680

**Closed by MetrosexualGarbodor** 2022-02-24 12:07 UTC
