### ISSUE TITLE
Issues with the start-up 

### ISSUE THREAD

**Issue by RainbowSnowZ** [Ryujinx/Ryujinx-Games-List#4377] opened 2023-01-21 20:04 UTC
### Game Name

Skylanders Imaginators

### Game Update Version

1.1.1

### Emulator Build Version

1.1.583

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Ryzen 5 3600
- ##### GPU: Sapphire Radeon RX 590 8 Go - Nitro+ GDDR5
- ##### RAM: 32GB

### Game State

The game keep crashing into the loading screen and I don't know what to do.

### Log File

[Ryujinx_1.1.583_2023-01-21_20-39-57.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10472926/Ryujinx_1.1.583_2023-01-21_20-39-57.log)

**Comment by MetrosexualGarbodor** [comment] 2023-01-21 20:07
Duplicate of #1532

**Closed by MetrosexualGarbodor** 2023-01-21 20:07 UTC
