### ISSUE TITLE
Sphynx and the Mummy's Curse - 0100BD500BA94000

### ISSUE THREAD

**Issue by Djipi71** [Ryujinx/Ryujinx-Games-List#3514] opened 2021-04-13 06:52 UTC
Game Update Version : 1.0.0 - 32bits game

Current on master : 1.0.6829

The game only shw black screen , after long time to way we can listen sound crackling but no graphism.

Last error returned:

00:01:48.241 |S| HLE.OsThread.9 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 4294967296 ; sixAxisSensorHandle: 131075 ; isAtRest: True}
00:01:48.241 |S| HLE.OsThread.9 ServiceHid IsVibrationPermitted: Stubbed. {_vibrationPermitted: False}

Hardware Specs : 

CPU: i7 9900
GPU: NVIDIA RTX 2070
RAM: 32GB)

Log file :
[Ryujinx_1.0.6829_2021-04-13_08-44-34.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6301764/Ryujinx_1.0.6829_2021-04-13_08-44-34.log)

**Comment by SeraUQ** [comment] 2021-04-13 09:19
closing as duplicate of #710

**Closed by SeraUQ** 2021-04-13 09:19 UTC
