### ISSUE TITLE
Super mario rpg crashing issue

### ISSUE THREAD

**Issue by KamranNosrati** [Ryujinx/Ryujinx-Games-List#4865] opened 2024-01-29 11:20 UTC
### Game Name

super mario RPG

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1141

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: ( i7-13700k)
- ##### GPU: (NVIDIA RTX 4080)
- ##### GPU Driver version: (545.84)
- ##### RAM: ( 32GB)

### Game State

 |E| HLE.OsThread.& Application : Unhandled exception caught: System.Reflection. TargetInvocationException: Exception has been thrown by the targe of an invocation.
LIbHac.Common.HorizonResultException: ResultFsHonRealDataVer|f1cationFalled (2002-4604) : Hash error!
at LibHac.Common. ThrowHelper. ThrowResult (Result result, String wessage)
at LIbHac. Tools. FsSysten. IntegrityVer1ficationStorage.ReadImpl(Int64 offset, Span*1 destination, IntegritycheckLevel IntegrityCheckLevel
LibHac.Tools.FsSystem.CachedStorage.Readslock(CacheBlockblock,Int64Index)
at
LibHac. Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
Libac.Tools.FsSysten.CachedStorage.Read(Int64 offset, Span"1 destination) at LibHiac.Tools.FsSysten.StorageStrean.Read(Byte(]buffer, Int32 offset, Int32 count)
at System.I0.Stream.Read(Span* 1)
at LibHac.Tools.Fssystem.Streanstorage.Read(Int64 offset, Span' 1 destination)
at Ryujinx.HLE.HOS.Services.Fs.FilesystemProxy.IStorage.Read(ServiceCtxcontext)inD:\a\Ryujinx\Ryujinx\sre\Ryug!
Storage.cs:line 35
at Invokestub_IStorage.Read(Object, Span' 1)
at

**Comment by piplup55** [comment] 2024-01-29 11:42
duplicate of #4811

[redump your game](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error)

**Closed** 2024-01-29 13:21 UTC

**Comment by KamranNosrati** [comment] 2024-01-29 18:47
> duplicate of #4811
> 
> [redump your game](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error)

there is no need for dumping the game,to fix the issue all you have to do is disabling “Enable FS Integrity Checks” option

**Comment by KamranNosrati** [comment] 2024-02-04 10:58
why did you delete my comment?😐
