### ISSUE TITLE
## Diablo III: Eternal Collection - 01001B300B9BE000 [proposed Label] crash

### ISSUE THREAD

**Issue by valerian2** [Ryujinx/Ryujinx-Games-List#3619] opened 2021-05-31 17:39 UTC
# Diablo III: Eternal Collection

#### Current on master : 1.0.6895

Game is heavily plagued by MEM access violations. Crashes randomly, sometimes immediately, sometimes after 5 or so minutes.

#### Last error returned.
```
00:03:05.249 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:03:05.269 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
```

#### Log file :

*[Ryujinx_1.0.6895_2021-05-29_16-06-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6564799/Ryujinx_1.0.6895_2021-05-29_16-06-45.log)*

**Comment by gdkchan** [comment] 2021-05-31 18:26
Closing as duplicate of #90. Please post tests on the existing issue.

**Closed by gdkchan** 2021-05-31 18:26 UTC

**Comment by valerian2** [comment] 2021-05-31 18:34
I had already posted but nobody answered me suddenly I wanted to try to do a new issue
