### ISSUE TITLE
明治活劇 ハイカラ流星組 －成敗しませう、世直し稼業－ - 0100EA100DF92000

### ISSUE THREAD

**Issue by bluebanana2021** [Ryujinx/Ryujinx-Games-List#4030] opened 2022-09-12 00:07 UTC
## Game Name
明治活劇 ハイカラ流星組 －成敗しませう、世直し稼業－

#### Graphics Backend : Vulkan v1.2.188, Driver v2.0.198

Crash at start.

```
Last error returned.
The instruction at 0x0000000000307138 (opcode 0xe320f004) is undefined!
```

#### Outstanding Issues:
https://github.com/Ryujinx/Ryujinx/issues/3686

#### Log file :
[Ryujinx_1.1.264_2022-09-12_08-14-13.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9543781/Ryujinx_1.1.264_2022-09-12_08-14-13.log)

**Comment by gdkchan** [comment] 2022-09-12 01:42
Possible duplicate of #2575.

**Comment by EmulationFanatic** [comment] 2022-09-13 11:38
Closing as duplicate.

**Closed by EmulationFanatic** 2022-09-13 11:38 UTC
Labels: status-nothing, 32-bit
