### ISSUE TITLE
Kirby Star Allies - 01007E3006DDA000

### ISSUE THREAD

**Issue by nyanyanyanyanyanyanyanya** [Ryujinx/Ryujinx-Games-List#3891] opened 2022-05-10 18:53 UTC
#### Current on `master` : 1.1.119

In gameplay sections, most things such as characters, and large parts of worlds/levels are displayed black. This causes ladders and enemies to be invisible depending on the level in the first world. 
After the end of the first world, it becomes practically unplayable.

```
Last error returned.
00:06:20.064 |E| HLE.OsThread.13 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
```

#### Screenshots :

![20220510200000_1](https://user-images.githubusercontent.com/105312395/167698772-18a7a656-817d-43bd-883f-71bcc10b69cd.jpg)
![20220428192713_1](https://user-images.githubusercontent.com/105312395/167698777-a7f045d8-097e-4bd6-81f7-c13fe747d8bc.jpg)
![20220428192656_1](https://user-images.githubusercontent.com/105312395/167698780-238ac21a-ba28-4564-8d4f-716fa5062a75.jpg)
![20220427120114_1](https://user-images.githubusercontent.com/105312395/167698783-51aa9ffb-4feb-41a8-9097-9ef9566cd534.jpg)
![20220427115248_1](https://user-images.githubusercontent.com/105312395/167698784-73178dd7-46b2-458c-a018-56385827506b.jpg)

#### Log file :

[Ryujinx_1.1.119_2022-05-10_19-54-21.tar.gz](https://github.com/Ryujinx/Ryujinx-Games-List/files/8664128/Ryujinx_1.1.119_2022-05-10_19-54-21.tar.gz)

**Comment by MetrosexualGarbodor** [comment] 2022-05-10 18:57
Duplicate of #45.

**Closed by MetrosexualGarbodor** 2022-05-10 18:57 UTC
