### ISSUE TITLE
Go Rally - 010055A0161F4000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#4519] opened 2023-03-23 02:00 UTC
### Game Name

Go Rally

### Game Update Version

1.0.0

### Emulator Build Version

1.1.677

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- #### GPU: GTX 1660 SUPER 6GB
- #### CPU: INTEL I5 8400
- #### RAM: KINGSTON DDR4 16GB

### Game State

The game is reversed within the game. It is not possible to continue playing ( but in the menu page Normal display game is not inverted )

### Screenshots

![bandicam 2023-03-23 08-37-20-723](https://user-images.githubusercontent.com/35269098/227078826-de9316ad-65fd-4ce9-b166-a67d0333ba92.jpg)
![bandicam 2023-03-23 08-37-33-953](https://user-images.githubusercontent.com/35269098/227078835-7308fd69-d7da-4842-b183-d80f44b5c3f6.jpg)
![bandicam 2023-03-23 08-37-36-699](https://user-images.githubusercontent.com/35269098/227078848-63ff81f2-d381-441d-a34c-875ab4d2a324.jpg)
![bandicam 2023-03-23 08-37-48-467](https://user-images.githubusercontent.com/35269098/227078853-5acd3859-73d7-41a9-8d6b-16b05bedf6f2.jpg)
![bandicam 2023-03-23 08-38-16-442](https://user-images.githubusercontent.com/35269098/227078863-7cefb029-910a-41f9-a402-1ba8611b97f3.jpg)
![bandicam 2023-03-23 08-38-27-078](https://user-images.githubusercontent.com/35269098/227078865-b051f038-40e0-425b-9a35-eaef35e9b2a2.jpg)
![bandicam 2023-03-23 08-39-00-149](https://user-images.githubusercontent.com/35269098/227078870-939c3e68-742c-48a1-bce2-4057b7c27de1.jpg)
![bandicam 2023-03-23 08-38-38-596](https://user-images.githubusercontent.com/35269098/227078877-48452a0e-282b-44e1-8943-cbcd3f4c0c26.jpg)

**Comment by MetrosexualGarbodor** [comment] 2023-03-23 02:04
Duplicate of #4384

**Closed by MetrosexualGarbodor** 2023-03-23 02:04 UTC
