### ISSUE TITLE
Super Mario Bros. Wonder - 010015100b514000

### ISSUE THREAD

**Issue by FiFo101SVK** [Ryujinx/Ryujinx-Games-List#4784] opened 2023-10-22 11:12 UTC
### Game Name

Super Mario Wonder

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1059

### Graphics Backend

Vulkan

### Macbook M2 Pro 14"
- ##### CPU: *M2 Pro 10c*
- ##### GPU: *M2 Pro 16c*
- ##### RAM: *16GB*

### Game State

Having to make my own shaders, it was really quick and ran well. If you already have shaders, the game should run perfectly without any problems. I experienced just a few stutters when I entered a completely new area, but it doesn't affect the game. The audio is also perfect without stutters

**Comment by MutantAura** [comment] 2023-10-22 11:15
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/4776
There is only a single report forum per title.

**Closed by MutantAura** 2023-10-22 11:15 UTC
