### ISSUE TITLE
mario party superstars minigame graphics problem

### ISSUE THREAD

**Issue by unuruu5760** [Ryujinx/Ryujinx-Games-List#4001] opened 2022-08-18 12:18 UTC
nvdia 512.95
ryujinx 1.1.222 
mario party superstars 1.0.0
![2022-08-18 21 13 40](https://user-images.githubusercontent.com/69958962/185392560-87124aa4-0b30-4041-9893-a7eb69d2f17b.png)
Graphics problems occur in both OpenGL and Vulkan. There is no red light.
Same problem for both upscaling 1x and 2x

**Comment by EmulationFanatic** [comment] 2022-08-18 12:26
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3752
Please post pertinent details in the original game issue.

**Closed by EmulationFanatic** 2022-08-18 12:26 UTC
