### ISSUE TITLE
Persona 5 Royal frame rate on Apple M1

### ISSUE THREAD

**Issue by Watchdual** [Ryujinx/Ryujinx-Games-List#4651] opened 2023-06-18 19:58 UTC
### Game Name

Persona 5 Royal

### Game Update Version

1.0.2

### Emulator Build Version

1.1.1897

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Apple M1 8 cores 
- ##### GPU: Apple M1 
- ##### RAM: 8 GB

### Game State

The game loads just fine and I haven't experienced any crashes. Once gameplay starts, the frame rate drops to about 15fps and is quite unplayable.

**Comment by MetrosexualGarbodor** [comment] 2023-06-22 17:05
Duplicate of #4086

**Closed by MetrosexualGarbodor** 2023-06-22 17:05 UTC
