### ISSUE TITLE
No Man's Sky

### ISSUE THREAD

**Issue by Mouseunder** [Ryujinx/Ryujinx-Games-List#4469] opened 2023-02-25 15:14 UTC
### Game Name

No Man's Sky

### Game Update Version

4.1.0

### Emulator Build Version

1.1.642

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

CPU: Intel(R) Core(TM) i7-8550U (1.8 - 4.0 Ghz, 8 threads)
GPU: AMD RX 560 Mobile (4 GB VRAM)
RAM: 8 GB DDR4 (2400 Mhz)

### Game State

Game doesn't launch.

### Log File

[Ryujinx_1.1.642_2023-02-25_18-06-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10831523/Ryujinx_1.1.642_2023-02-25_18-06-24.log)

**Comment by gdkchan** [comment] 2023-02-25 15:16
Duplicate of #4226.

**Closed by gdkchan** 2023-02-25 15:16 UTC

**Comment by gdkchan** [comment] 2023-02-25 15:18
(You should post the test results in the existing issue).
