### ISSUE TITLE
Pokemon Brilliant Diamond crashes randomly

### ISSUE THREAD

**Issue by zawad700** [Ryujinx/Ryujinx-Games-List#4452] opened 2023-02-22 07:27 UTC
### Game Name

Pokemon Brilliant Diamond

### Game Update Version

1.0.0

### Emulator Build Version

1.1.0-macos1

### Graphics Backend

Vulkan

### Hardware Specs

M1 macbook air 8gb

### Game State

The game loads and works with minor graphical issues, but the game crashes randomly and suddenly. It doesn't seem to have a trigger to crash just crashes at absolute random timing.

**Comment by MetrosexualGarbodor** [comment] 2023-02-22 07:34
Duplicate of #3776

**Closed by MetrosexualGarbodor** 2023-02-22 07:34 UTC
