### ISSUE TITLE
The legend of zelda âge of calamity

### ISSUE THREAD

**Issue by Kemikkk** [Ryujinx/Ryujinx-Games-List#3915] opened 2022-06-19 15:42 UTC
A## Game Name
Thé legend of zelda âge of calamity
#### Game Update Version : 
Version 1.3.0
#### Current on `master` : Build.                                 Version : 
Ryujin x 1.48

the game starts well, I see the cutscene but when I have to play I have a black screen with the map and the words of a character the only thing we see are blue explosions in a black world, impossible to to play.

##### RAM: *(e.g. 6 GB
Status
 Crash ,menus, 
# # # # status: crash, menus

**Comment by Kemikkk** [comment] 2022-06-19 15:46
Status:crash

**Comment by Eli0t77** [comment] 2022-06-19 16:06
That GPU isn't going to run age of calamity although you might have better luck using the vulkan build

Also this is the page for the game
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2862

**Comment by MutantAura** [comment] 2022-06-19 16:17
duplicate of #2862

**Closed by MutantAura** 2022-06-19 16:17 UTC

**Comment by Kemikkk** [comment] 2022-06-19 18:11
I am sorry ,I speak french ,Please help me I love Zelda :J'arrive pourtant a jouer a botw , Skyward Sword ,link awakenning
