### ISSUE TITLE
Monster Hunter Rise[0100b04011742000] light and shadow keep flickering

### ISSUE THREAD

**Issue by cnmmg** [Ryujinx/Ryujinx-Games-List#4899] opened 2024-03-17 03:46 UTC
### Game Name

Monster Hunter Rise

### Game Update Version

15.0.1

### Emulator Build Version

1.1.1231

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *(m3 max)*
- ##### GPU: *(m3 max)*
- ##### GPU Driver version: *(system version 14.4)*
- ##### RAM: *(36GB)*

### Game State

There is no problem with the base version, but after updating to sunbreak, the lights and shadows start to flicker in some places, which seriously affects the gameplay.
Sometimes, ryujinx will crash during gameplay.

### Screenshots

<img width="1134" alt="截屏2024-03-17 11 34 40" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/130685213/35262452-7b86-4902-b28d-2f2b289fea8a">
<img width="849" alt="截屏2024-03-17 11 35 24" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/130685213/c73c1715-dcd9-4c34-9280-703f166f51c6">
<img width="1336" alt="截屏2024-03-17 11 35 09" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/130685213/a0bf0e51-fbd7-47d2-97dd-7b526aa1739d">

### Log File

[crash1.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/14626126/crash1.txt)

**Comment by piplup55** [comment] 2024-03-17 07:34
duplicate of #3465

**Closed by piplup55** 2024-03-17 07:34 UTC
