### ISSUE TITLE
Nintendo Switch Sports Black Screen and Crashing

### ISSUE THREAD

**Issue by SamirChicago21** [Ryujinx/Ryujinx-Games-List#5018] opened 2024-07-25 01:27 UTC
### Game Name

Nintendo Switch sports

### Game Update Version

1.0.0

### Emulator Build Version

Ryujinx 1.1.1359, Firmware - 17.0.1

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Intel(R) Core(TM) i7-8665U CPU @1.90GHz
- ##### GPU: Intel(R) UHD Graphics 620
- ##### GPU Driver version: 30.0.101.1404
- ##### RAM: 16 GB

### Game State

So, I have Ryujinx up and running fine. The problem is that when I try booting up Nintendo Switch Sports the game shows be a black screen, and then a 1-2 second menu (in screenshots) before crashing.

### Screenshots

![Screenshot 2024-07-24 201927](https://github.com/user-attachments/assets/cdc7570b-dfae-4104-b097-91f56591d8ef)
![Screenshot 2024-07-24 193641](https://github.com/user-attachments/assets/2119c7f8-7980-47bf-8a7d-caf5d140e201)

### Log File

[Ryujinx_1.1.1359_2024-07-24_20-07-19.log](https://github.com/user-attachments/files/16369027/Ryujinx_1.1.1359_2024-07-24_20-07-19.log)

**Comment by MetrosexualGarbodor** [comment] 2024-07-25 01:31
Duplicate of #4079

**Closed by MetrosexualGarbodor** 2024-07-25 01:31 UTC
