### ISSUE TITLE
Untitled Goose Game - Adding update 1.0.7 causes crash

### ISSUE THREAD

**Issue by syberphunk** [Ryujinx/Ryujinx-Games-List#2565] opened 2020-09-25 21:55 UTC
#### Current on Build Version : 1.0.0-ldn1 and 1.0.5428

ryujinx GUI crashes when adding game update 1.0.7, freezes and then have to force close - update is then not added.

```
Last error returned.
00:00:09.986 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at LibHac.FsSystem.StorageExtensions.ToArray[T](IStorage storage)
   at LibHac.FsSystem.RomFs.RomFsDictionary`1..ctor(IStorage bucketStorage, IStorage entryStorage)
   at LibHac.FsSystem.RomFs.HierarchicalRomFileTable`1..ctor(IStorage dirHashTable, IStorage dirEntryTable, IStorage fileHashTable, IStorage fileEntryTable)
   at LibHac.FsSystem.RomFs.RomFsFileSystem..ctor(IStorage storage)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(IStorage storage, NcaFsHeader header)
   at Ryujinx.Ui.TitleUpdateWindow.AddUpdate(String path, Boolean showErrorDialog) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx\Ui\TitleUpdateWindow.cs:line 101
   at Ryujinx.Ui.TitleUpdateWindow.AddButton_Clicked(Object sender, EventArgs args) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx\Ui\TitleUpdateWindow.cs:line 162
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

#### Log file :
[Ryujinx_2020-09-25_22-49-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5285545/Ryujinx_2020-09-25_22-49-15.log)

[Ryujinx_2020-09-26_09-56-25.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5286435/Ryujinx_2020-09-26_09-56-25.log)

**Comment by GamerzHell9137** [comment] 2020-09-25 22:57
Don't use ldn, use the master builds.

**Comment by syberphunk** [comment] 2020-09-26 08:58
Updated issue with information about latest build also causing the error as well as ldn release.

**Comment by GamerzHell9137** [comment] 2020-09-26 09:10
https://github.com/Ryujinx/Ryujinx-Games-List/issues/535

**Comment by SeraUX** [comment] 2020-09-26 09:28
closed as its a duplicate of #535

**Closed by SeraUX** 2020-09-26 09:28 UTC

**Comment by syberphunk** [comment] 2020-09-26 09:46
@SeraUX Are you wanting this to be reposted on the other ticket, or is being linked to this one OK ?

**Comment by SeraUX** [comment] 2020-09-26 09:49
post it as a comment on #535

**Comment by syberphunk** [comment] 2020-09-26 13:18
> post it as a comment on #535

Done, thank you.
