### ISSUE TITLE
Nintendo Switch Sports - 0100D2F00D5C0800

### ISSUE THREAD

**Issue by skywolf123** [Ryujinx/Ryujinx-Games-List#4738] opened 2023-09-11 04:18 UTC
### Game Name

Nintendo Switch Sports

### Game Update Version

v1.4.0

### Emulator Build Version

test-ava-ryujinx-1.1.1011-win_x64

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *i9-12900H*
- ##### GPU: *NVIDIA GeForce RTX 3070 Laptop GPU*
- ##### RAM: *16GB*

### Game State

I can enter the game, after a few pages of normal prompts, click Next, and the simulator crashes automatically shut down when I enter the game screen.
log error: Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".

### Log File

[Ryujinx_1.1.1011_2023-09-11_12-05-53.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12572160/Ryujinx_1.1.1011_2023-09-11_12-05-53.log)

**Comment by OldManKain** [comment] 2023-09-11 05:09
Duplicate of #4079

**Closed by OldManKain** 2023-09-11 05:09 UTC
