### ISSUE TITLE
Dragon Quest Builders 2 display issue on Mac M1

### ISSUE THREAD

**Issue by KamdanMan** [Ryujinx/Ryujinx-Games-List#4942] opened 2024-04-25 00:04 UTC
### Game Name

Dragon Quest Builders 2

### Game Update Version

1.7.3

### Emulator Build Version

1.1.1291

### Graphics Backend

Vulkan

### Hardware Specs

Silicon Mac M1

### Game State

Black screen on Macbook Pro M1 after character selection. The game is still running, and you can move etc. But the screen is just black, only UI is visible.

**Comment by ekuland** [comment] 2024-04-25 01:12
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/188

**Closed by ekuland** 2024-04-25 01:12 UTC
