### ISSUE TITLE
GRAPHIC PROBLEM IN RYUJINX MAC

### ISSUE THREAD

**Issue by LUKMER** [Ryujinx/Ryujinx-Games-List#4672] opened 2023-07-04 07:22 UTC
### Game Name

OCTOPATH TRAVELER 2

### Game Update Version

1.0.2

### Emulator Build Version

1.1.0

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Software
- ##### GPU: *Apple M2 Ultra
- ##### RAM: *128

### Game State

The game goes dark in the rooms.

### Screenshots

<img width="1271" alt="Captura de pantalla 2023-07-04 a las 7 58 43" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/93650882/d8ba2695-4c8d-4677-89cd-0dce68473c07">

### Log File

[Ryujinx_ 1.1.0-macos1_2023-07-04_07-54-06.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11945921/Ryujinx_.1.1.0-macos1_2023-07-04_07-54-06.log)
[Ryujinx_ 1.1.0-macos1_2023-07-04_07-54-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11945923/Ryujinx_.1.1.0-macos1_2023-07-04_07-54-40.log)
[Ryujinx_ 1.1.0-macos1_2023-07-04_07-55-36.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11945924/Ryujinx_.1.1.0-macos1_2023-07-04_07-55-36.log)

**Comment by LUKMER** [comment] 2023-07-04 07:35
This is the same scene but playing on PC
![WhatsApp Image 2023-07-04 at 9 33 54 AM](https://github.com/Ryujinx/Ryujinx-Games-List/assets/93650882/1ac0a9e7-b3d3-40c7-b33d-db917a486301)

**Comment by MetrosexualGarbodor** [comment] 2023-07-04 16:04
Duplicate of #4465

**Closed by MetrosexualGarbodor** 2023-07-04 16:04 UTC
