### ISSUE TITLE
Minecraft - 0100D71004694800

### ISSUE THREAD

**Issue by GuiGui-OfficielYT** [Ryujinx/Ryujinx-Games-List#4854] opened 2024-01-03 08:17 UTC
### Game Name

Minecraft

### Game Update Version

1.20.51

### Emulator Build Version

1.1.1102

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Intel(R) N95 1.70 GHz*
- ##### GPU: *Intel(R) UHD Graphics*
- ##### GPU Driver version: *31.0.101.4889*
- ##### RAM: *16GB*

### Game State

Doesn't boot at all

### Log File

[Ryujinx_1.1.1102_2024-01-03_03-06-34.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13816816/Ryujinx_1.1.1102_2024-01-03_03-06-34.log)

**Comment by piplup55** [comment] 2024-01-04 03:04
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/2551

**Closed** 2024-01-04 11:09 UTC
