### ISSUE TITLE
Light makes the screen purple and glitch out

### ISSUE THREAD

**Issue by Attar18** [Ryujinx/Ryujinx-Games-List#4855] opened 2024-01-05 09:13 UTC
### Game Name

Little Nightmares II

### Game Update Version

1.4

### Emulator Build Version

1.1.1104

### Graphics Backend

OpenGL

### Hardware Specs

Apple M1 chip
8-core CPU with 4 perform­ance cores and 4 efficiency cores
7-core GPU, 8-core GPU
16-core Neural Engine

### Game State

Besides the light glitching, the background and objects occasionally glitches, appearing and disappearing fast

### Screenshots

![IMG_7219](https://github.com/Ryujinx/Ryujinx-Games-List/assets/155722291/7db1c603-b897-4089-bc9b-8db28aa01e76)

**Comment by piplup55** [comment] 2024-01-05 19:19
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3392

**Closed** 2024-01-05 19:20 UTC
