### ISSUE TITLE
Pokemon Legends: Arceus - crash on startup

### ISSUE THREAD

**Issue by iipamonkey** [Ryujinx/Ryujinx-Games-List#5006] opened 2024-07-02 15:57 UTC
### Game Name

Pokemon Legends: Arceus

### Game Update Version

1.1.1

### Emulator Build Version

1.1.1340

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: i5-13600K
- ##### GPU: NVIDIA RTX 4070ti
- ##### GPU Driver version: 55.99.0.0
- ##### RAM: 32GB

### Game State

Game crashes immediately on startup and Ryujinx closes.

### Log File

[Ryujinx_1.1.1340_2024-07-02_10-49-08.log](https://github.com/user-attachments/files/16071199/Ryujinx_1.1.1340_2024-07-02_10-49-08.log)

**Comment by MetrosexualGarbodor** [comment] 2024-07-02 16:01
There's barely any information in this log. Please use Discord for support instead of opening issues. Closing as duplicate of #3817.

**Closed by MetrosexualGarbodor** 2024-07-02 16:01 UTC
