### ISSUE TITLE
Moero Crystal H

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2839] opened 2020-11-14 17:22 UTC
#### Current on `master` : 1.0.5683

Nothing seems to happen, I wait for it to load 10-20 minutes, still spam message HidServer ServiceHid GetActualVibrationValue: Stubbed. But the game is still running but nothing happens after 20 minutes, I will leave the logs, it probably won't help.

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-11-15 00-12-55-979](https://user-images.githubusercontent.com/35269098/99152933-a8fe6300-26d7-11eb-9353-99e47da8b692.jpg)

#### Logs :

[MCH.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5541156/MCH.log)

**Comment by EmulationFanatic** [comment] 2020-11-15 00:30
Closing as duplicate of #1769

**Closed by EmulationFanatic** 2020-11-15 00:30 UTC
Labels: duplicate
