### ISSUE TITLE
Gensou Manege

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#2541] opened 2020-09-20 21:38 UTC
**Game Name :** Gensou Manège

**Game Update Version :** 1.0.1

**Current on `master` : Commit Id *or* Build Version :** 1.0.5391

Game runs smooth, can be played normally - including the minigame. However, images sometimes glitch, and characters' expressions (eyes and mouth) are often swapped with each other. Videos (such as title intro and opening) are broken for the lower-half of the screen; the audio and what appears on the upper-half runs fine.

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Screenshots :**

![Ryujinx_VMC93Q724d](https://user-images.githubusercontent.com/71459954/93722783-8104ee80-fbc3-11ea-917c-ffa140e3c7ff.png)
![Ryujinx_uoOOwZRnTu](https://user-images.githubusercontent.com/71459954/93722786-84987580-fbc3-11ea-856c-01ae89e0a88b.png)
![Ryujinx_LYQ1zmsrnD](https://user-images.githubusercontent.com/71459954/93722811-aa257f00-fbc3-11ea-8a51-356d24800b36.jpg)
![Ryujinx_kUk4wHYsoh](https://user-images.githubusercontent.com/71459954/93722817-b578aa80-fbc3-11ea-8bf8-329229da00e2.png)
![Ryujinx_fmSD9aRu1c](https://user-images.githubusercontent.com/71459954/93722826-c5908a00-fbc3-11ea-8a5f-9809ef827c7a.png)
![Ryujinx_A7vyf2P1j6](https://user-images.githubusercontent.com/71459954/93722829-ccb79800-fbc3-11ea-967f-2de80b7c2378.png)
![Ryujinx_9z37DwdTYE](https://user-images.githubusercontent.com/71459954/93722835-d2ad7900-fbc3-11ea-8060-ecd37fddb08e.png)
![Ryujinx_5l2BMeqSjh](https://user-images.githubusercontent.com/71459954/93722840-d7722d00-fbc3-11ea-86d3-d0d949ad52c6.jpg)
![Ryujinx_9THfYMZNkZ](https://user-images.githubusercontent.com/71459954/93722841-d93bf080-fbc3-11ea-82d7-e6116f3c78ae.png)
![Ryujinx_S4FkD5KNqG](https://user-images.githubusercontent.com/71459954/93722843-e1942b80-fbc3-11ea-87a4-9b82e9ee2080.png)
![Ryujinx_FVICd569Oo](https://user-images.githubusercontent.com/71459954/93722849-e5c04900-fbc3-11ea-854e-65943aef3055.png)
![Ryujinx_Z8n38DLjwR](https://user-images.githubusercontent.com/71459954/93722853-eeb11a80-fbc3-11ea-9f19-769c15855ecf.png)

**Log file :**
[Ryujinx_2020-09-21_03-27-08.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5252712/Ryujinx_2020-09-21_03-27-08.log)

**Comment by SeraUX** [comment] 2020-09-21 13:56
Duplicate of #2048

**Closed by SeraUX** 2020-09-21 13:56 UTC
Labels: gpu, status-ingame
