### ISSUE TITLE
skyrim

### ISSUE THREAD

**Issue by erilson123** [Ryujinx/Ryujinx-Games-List#5046] opened 2024-08-27 21:05 UTC
### Game Name

Skyrim

### Game Update Version

1.00

### Emulator Build Version

ryujinx

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

dv

### Screenshots

fd

### Log File

dfd

**Comment by MutantAura** [comment] 2024-08-27 21:07
Duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/1536

**Closed by MutantAura** 2024-08-27 21:07 UTC
