### ISSUE TITLE
Daemon X Machina

### ISSUE THREAD

**Issue by Niwu-34** [Ryujinx/Ryujinx-Games-List#2659] opened 2020-10-08 19:31 UTC
**Daemon X Machina**
*V1.3.1*
Master: Ryujinx Version: 1.0.5485

The game boots and run with the issues listed in "Outstanding Issues"

Hardware Specs
Microsoft *Windows* 10.0.19041
CPU: R53600
GPU: Rx 570 (Driver: 20.9.2)
RAM: 16GB

Based on Issue #1718

Outstanding Issues:
- UE4Game (Ryujinx/Ryujinx#1282)
- Doesn't let u enter a name when creating a charachter which makes it neccesary to use a save file. (Similar to Monster Hunter)
- Huge Graphical bugs ingame (Menu looks fine)

Screenshots:
https://user-images.githubusercontent.com/70352958/95490137-17912800-0998-11eb-88b5-f02297803a6c.png
https://user-images.githubusercontent.com/70352958/95490273-4c9d7a80-0998-11eb-9635-aa46307e74e2.png

**Comment by EmulationFanatic** [comment] 2020-10-08 19:37
Closing as duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/1718

**Closed by EmulationFanatic** 2020-10-08 19:37 UTC
Labels: duplicate
