### ISSUE TITLE
Luigi's Mansion 2 HD, half the screen good and half bad

### ISSUE THREAD

**Issue by gabri25ele** [Ryujinx/Ryujinx-Games-List#5013] opened 2024-07-13 07:27 UTC
### Game Name

Luigi's Mansion 2 HD

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1345

### Graphics Backend

Vulkan

### Hardware Specs

CPU: AMD 5900X
GPU: RX 6900 XTX
GPU Driver version: 24.6.1
RAM: 32 GB DDR4 3600

### Game State

the screen seems split, half done well, half done badly during cutscenes, in game it looks even worse. (tried suyu, no one problem)

### Screenshots

![Senza titolo](https://github.com/user-attachments/assets/abcf3164-1e4e-4c02-a84d-09e4b2b17ef2)

![S3enza titolo](https://github.com/user-attachments/assets/922d2c9d-b6d9-4bb1-bd07-b35619209427)

![S33enza titolo](https://github.com/user-attachments/assets/2f766126-7ae0-43f8-b188-1fc9d91ec4ae)

![dfd](https://github.com/user-attachments/assets/b66a443e-c9df-4e0a-92b3-7942164a730a)

![S3434enza titolo](https://github.com/user-attachments/assets/1bc321fa-44a2-46c3-bb49-ebea943b1b60)

### Log File

[Ryujinx_1.1.1345_2024-07-13_09-25-36.log](https://github.com/user-attachments/files/16201243/Ryujinx_1.1.1345_2024-07-13_09-25-36.log)

**Comment by piplup55** [comment] 2024-07-13 08:17
duplicate of #5003

**Closed by piplup55** 2024-07-13 08:17 UTC
