### ISSUE TITLE
Pokemon sword 4th gym mission

### ISSUE THREAD

**Issue by SugarCubeOfSalt** [Ryujinx/Ryujinx-Games-List#3636] opened 2021-06-27 23:02 UTC
Pokemon sword

v1.0.0

1.0.6939

almost impossible to beat

**Comment by AcK77** [comment] 2021-06-27 23:07
Duplicate of #232

**Closed by AcK77** 2021-06-27 23:07 UTC

**Comment by SugarCubeOfSalt** [comment] 2021-06-27 23:11
> Duplicate of #232

its not though theyre completely different im asking for advice on how to beat the 4th gym mission on keyboard

**Comment by AcK77** [comment] 2021-06-27 23:18
This is for game report, not user support, if you needs support I suggest you to come on our discord server.
Thanks!
