### ISSUE TITLE
eBaseball POWERUFL PRO YAKYUU 2022 | Crash on startup

### ISSUE THREAD

**Issue by abver090** [Ryujinx/Ryujinx-Games-List#4889] opened 2024-03-10 14:36 UTC
### Game Name

eBaseball POWERUFL PRO YAKYUU 2022

### Game Update Version

1.0.0

### Emulator Build Version

1.1.2222

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *i5-4680*
- ##### GPU: *AMD HD 7700 Radeon*
- ##### GPU Driver version: *27.20.20913.2000*
- ##### RAM: *8GB*

### Game State

Game doesn't start at all. Emulator crashes on loading the game. Nothing much to say, really.

### Log File

[Ryujinx_1.1.1222_2024-03-10_21-29-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14550555/Ryujinx_1.1.1222_2024-03-10_21-29-58.log)
[Ryujinx_1.1.1222_2024-03-10_21-34-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14550566/Ryujinx_1.1.1222_2024-03-10_21-34-46.log)

**Comment by ekuland** [comment] 2024-03-10 14:39
Duplicate of #4010

**Closed** 2024-03-10 14:39 UTC
