### ISSUE TITLE
Luigi's Mansion 3 mirror bug with vulkan - 0100dca0064a6000

### ISSUE THREAD

**Issue by Goodfeat** [Ryujinx/Ryujinx-Games-List#5051] opened 2024-09-03 01:34 UTC
### Game Name

Luigi's Mansion 3

### Game Update Version

1.0.0/1.4.0

### Emulator Build Version

1.1.1372

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: AMD 5800U
- ##### GPU: AMD RADEON  Graphics (Radv Renioir)
- ##### GPU Driver version: 4.6(Compatibility profile) Mesa 24.2.1, shaders 4.60, amd graphics api Opengl 3.0/glsl
- ##### RAM: 16GB (2gb integrated graphics)

### Game State

in some places where mirrors are installed, these mirrors are either black or partially working, but do not display the characters and part of the scenery

on Opengl mirrors work, but multiple colored graphic artifacts appear from the flashlight (it is impossible to play like this)

### Screenshots

black mirrows
![IMG_20240903_105907](https://github.com/user-attachments/assets/362573c0-2b64-4095-9bde-041324f7d248)

there is a mirror, but luigi is not displayed in it, and part of the decorations (the panel with buttons and side walls) are also not displayed
![IMG_20240903_105352](https://github.com/user-attachments/assets/b30ae1ad-9f4a-4986-8794-e3cc0a87eb4e)

### Log File

[Ryujinx_1.1.1372_2024-09-03_11-15-36.log](https://github.com/user-attachments/files/16842288/Ryujinx_1.1.1372_2024-09-03_11-15-36.log)

**Comment by piplup55** [comment] 2024-09-03 08:16
Duplicate of #207

**Closed by piplup55** 2024-09-03 08:16 UTC
