### ISSUE TITLE
Mario + Rabbids: Sparks of Hope 09/04/2023

### ISSUE THREAD

**Issue by TheTrueTekno** [Ryujinx/Ryujinx-Games-List#4730] opened 2023-09-05 01:00 UTC
### Game Name

Mario + Rabbids: Sparks of Hope

### Game Update Version

1.6.2225577

### Emulator Build Version

1.1.1008

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: AMD Ryzen 7 2700X
- ##### GPU: NVIDIA RTX 2070
- ##### RAM: 32GB
- ##### Storage: 4TB HDD
- ##### OS: Windows 10 Pro

### Game State

Game runs almost perfectly. The Ubisoft logo stutters when booting the game, and some cutscenes have a little bit of laggy audio. Currently on World 5 and no major or minor issues exist outside of the previously mentioned ones.

### Screenshots

![Screenshot (222)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/60714363/1912503f-c621-42d7-8f05-97f09b890a8a)
![Screenshot (223)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/60714363/40b1803d-d769-4645-b706-9cbd23ac77bb)
![Screenshot (224)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/60714363/94e3f089-26de-441b-969b-43265e2985d1)
![Screenshot (225)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/60714363/53c2e4bf-1484-418f-ba23-0283a680b9a0)

### Log File

[Ryujinx_1.1.1008_2023-09-04_20-43-11.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12517580/Ryujinx_1.1.1008_2023-09-04_20-43-11.log)

**Comment by OldManKain** [comment] 2023-09-05 13:56
Duplicate of #4089

**Closed by OldManKain** 2023-09-05 13:56 UTC

**Comment by Megasonic999** [comment] 2024-04-23 09:14
It crashes on startup for me
