### ISSUE TITLE
Pokémon Scarlet MacOS Crash

### ISSUE THREAD

**Issue by KiwiInFlight** [Ryujinx/Ryujinx-Games-List#4277] opened 2022-12-07 02:41 UTC
## Pokemon Scarlet

####1.0.1

##### RAM: 16GB

After selecting name and appearance, the autosave takes place, then the pkmn trainer contract is accepted, then music starts and a logo appears and the emulator freezes, simultaneously freezing the system then then the OS crashes and computer restarts.

#### Log file:

00:00:00.088 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.094 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.094 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.095 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.097 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.098 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.098 |I| Configuration LogValueChange: PreferredGpu set to: 0x8086_0x8A53
00:00:00.102 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.113 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.113 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.113 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.113 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.113 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.113 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.113 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.113 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.114 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.114 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.115 |I| Configuration LogValueChange: MemoryManagerMode set to: SoftwarePageTable
00:00:00.115 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.115 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.115 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.122 |N| Application PrintSystemInfo: Ryujinx Version:  1.1.0-macos1
00:00:00.131 |N| Application Print: Operating System: Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 (X64)
00:00:00.131 |N| Application Print: CPU: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz ; 8 logical
00:00:00.132 |N| Application Print: RAM: Total 16384 MiB ; Available Unknown
00:00:00.135 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.136 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.278 |I| Gpu : Backend Threading (Auto): True
00:00:00.633 |N| Application LoadGuestApplication: Using Firmware Version: 15.0.1
00:00:00.633 |I| Application LoadGuestApplication: Loading as XCI.
00:00:00.723 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A3D008C5C000
00:00:00.725 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A3D008C5C000
00:00:00.731 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.741 |I| Loader LoadExeFs: Loading rtld...
00:00:00.812 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.812 |I| Loader LoadExeFs: Loading main...
00:00:01.476 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\titan\v_1_0_0\rom_build\programs\prog\app\msvc\main_app\NX64\Release\main_app.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-13_3_5-Release
                   SDK MW+Nintendo+NintendoSDK_gRPC_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+NintendoSDK_OpenSSL_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+NintendoSDK_NPLN-1_4_1-Release
                   SDK MW+Nintendo+NintendoSDK_Google_APIs_For_NPLN-1_4_1-Release
                   SDK MW+Nintendo+PiaCommon-6_20_1
                   SDK MW+Nintendo+Pia-6_20_1
                   SDK MW+Nintendo+PiaLocal-6_20_1
                   SDK MW+Nintendo+PiaLan-6_20_1
                   SDK MW+Nintendo+PiaReckoning-6_20_1
                   SDK MW+Nintendo+PiaSession-6_20_1
                   SDK MW+Nintendo+PiaTransport-6_20_1
                   SDK MW+Nintendo+PiaNpln-6_20_1
                   SDK MW+NINTENDO+nlib_LZ4-22_0201
                   SDK MW+Nintendo+NintendoWare_Font-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-13_3_5-Release
                   SDK MW+Nintendo+NintendoWare_G3d-13_3_5-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-13_3_5-Release
                   SDK MW+Microsoft+Havok_AI-2021_1
00:00:01.477 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.531 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-13_3_5-Release
00:00:01.531 |I| Loader LoadExeFs: Loading sdk...
00:00:01.661 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 13.3.5
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_5-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-13_3_5-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-13_3_5-Release
00:00:01.699 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:04.422 |I| Ptc Load: Loaded Translation Cache (size: 169607062 bytes, translated functions: 46359).
00:00:04.442 |I| Ptc Load: Loaded Profiling Info (size: 145875 bytes, profiled functions: 46369).
00:00:04.565 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:04.566 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:04.607 |I| Loader LoadNsos: Loading image 2 at 0x000000000c3f9000...
00:00:04.611 |I| Loader LoadNsos: Loading image 3 at 0x000000000ca93000...
00:00:04.624 |I| ModLoader LoadCheats: Build ids found for title 0100A3D008C5C000:
    567CDD4C5251494C5CD70822E3CCC740C190C2B2000000000000000000000000
    CA44E7DD62E61A2A4E8889B3319AE173375770FD000000000000000000000000
    D0F13015E5BADF2243D60A2BC9B978DDDBA80608000000000000000000000000
    3644A6760469451CABC99F00C540ACC2A64AEE41000000000000000000000000
00:00:04.624 |I| Loader LoadNca: Application Loaded: Pokémon Scarlet v1.0.0 [0100a3d008c5c000] [64-bit]
00:00:04.665 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:04.687 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:05.152 |N| GUI.RenderThread Gpu PrintGpuInformation: Intel Intel(R) Iris(TM) Plus Graphics (Vulkan v1.2.231, Driver v0.2.2008)
00:00:05.163 |I| GPU.MainThread Gpu LoadShaders: Loading 183 shaders from the cache...
00:00:18.024 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:19.433 |I| HLE.GuestThread.16 Ptc LoadTranslations: 46357 translated functions loaded
00:00:19.450 |I| HLE.GuestThread.16 Ptc MakeAndSaveTranslations: 0 of 12 functions translated | Thread count: 7
00:00:19.772 |I| HLE.GuestThread.16 Ptc MakeAndSaveTranslations: 12 of 12 functions translated | Thread count: 7 in 0.3198444 s
00:00:20.013 |S| HLE.OsThread.17 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:20.032 |S| HLE.OsThread.17 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:20.033 |S| HLE.OsThread.17 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:20.034 |S| HLE.OsThread.17 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:20.055 |S| HLE.OsThread.17 ServicePctl Initialize: Stubbed. 
00:00:20.135 |W| HLE.GuestThread.16 KernelSvc : MapPhysicalMemory() = ResLimitExceeded
00:00:20.154 |S| HLE.OsThread.17 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:20.161 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:20.164 |I| GUI.WindowThread Hid SetupNpad: Disconnected Controller JoyconPair from Player1
00:00:20.168 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Handheld'
00:00:20.169 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:20.169 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 93 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:20.170 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:20.385 |I| HLE.OsThread.17 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:20.387 |I| HLE.OsThread.17 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:20.400 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:20.420 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:20.444 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:20.450 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:20.450 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:20.565 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:20.566 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:20.567 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:20.569 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:20.570 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:20.570 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:20.574 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:24.273 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:24.279 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV10
00:00:24.305 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:24.306 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:24.331 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:24.367 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:24.491 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:24.877 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:25.000 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 93 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:25.001 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:25.002 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:25.003 |S| HLE.OsThread.9 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: -4314676866561605632}
00:00:25.004 |S| HLE.OsThread.9 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: -4314676660403175424}
00:00:26.697 |S| HLE.OsThread.17 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72237707933630464}
00:00:26.701 |S| HLE.OsThread.17 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:26.701 |S| HLE.OsThread.17 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:26.725 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:28.565 |I| Ptc Save: Saved Translation Cache (size: 169629867 bytes, translated functions: 46371).
00:00:29.505 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:29.510 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:29.530 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:29.539 |S| HLE.OsThread.9 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5}
00:00:29.539 |S| HLE.OsThread.9 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541}
00:00:49.825 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 145880 bytes, profiled functions: 46370).
00:00:57.693 |S| HLE.OsThread.17 ServiceAm GetLibraryAppletLaunchableEvent: Stubbed. 
00:00:57.711 |I| HLE.OsThread.17 ServiceAm .ctor: Applet 'SoftwareKeyboard' created.
00:01:06.065 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:01:06.070 |I| Hid Configure: Configured Controller JoyconPair to Player1
00:01:19.832 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 145886 bytes, profiled functions: 46372).
00:01:49.805 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 145903 bytes, profiled functions: 46375).
00:02:10.277 |E| HLE.GuestThread.27 Gpu : VK Sync Object 7283 failed to signal within 1000ms. Continuing...
00:02:11.287 |E| HLE.GuestThread.29 Gpu : VK Sync Object 7283 failed to signal within 1000ms. Continuing...
00:02:19.781 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 145914 bytes, profiled functions: 46378).

**Comment by MetrosexualGarbodor** [comment] 2022-12-07 02:42
Duplicate of #4218

**Closed by MetrosexualGarbodor** 2022-12-07 02:42 UTC
