### ISSUE TITLE
白き聖灰の女王 for Nintendo Switch Black screen

### ISSUE THREAD

**Issue by gbqgbq** [Ryujinx/Ryujinx-Games-List#4913] opened 2024-03-31 07:08 UTC
### Game Name

白き聖灰の女王 for Nintendo Switch

### Game Update Version

1.02

### Emulator Build Version

1.1.1248

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-12700)*
- ##### GPU: *(e.g. NVIDIA RTX 3060TI)*
- ##### GPU Driver version: *(e.g. 551.61)*
- ##### RAM: *(e.g. 16GB)*

### Game State

The game has a black screen
![无标题](https://github.com/Ryujinx/Ryujinx-Games-List/assets/7303022/ddf27ad2-0f32-4057-a904-8a27be8bcb5e)
CG is normal
SUYU normal
![无标题1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/7303022/581cd3cb-eb05-45b4-a71b-00402c12ec8c)

**Comment by gdkchan** [comment] 2024-03-31 09:54
Duplicate of #3905.

**Closed by gdkchan** 2024-03-31 09:54 UTC
