### ISSUE TITLE
Pokemon Legends: Arceus

### ISSUE THREAD

**Issue by G-Migz** [Ryujinx/Ryujinx-Games-List#5010] opened 2024-07-06 09:41 UTC
### Game Name

Pokemon Legends Arceus

### Game Update Version

1.00

### Emulator Build Version

1.1.1340

### Graphics Backend

Vulkan

### Hardware Specs

I5-1235U
Intel Iris XE Graphics
16gb ram

### Game State

Game is playable i havent notice any issues

### Screenshots

![Screenshot 2024-07-06 173505](https://github.com/Ryujinx/Ryujinx-Games-List/assets/174666100/5c983adc-f88e-41ed-ab8c-7454062f4592)

### Log File

[Ryujinx_1.1.1340_2024-07-06_14-47-58.log](https://github.com/user-attachments/files/16115523/Ryujinx_1.1.1340_2024-07-06_14-47-58.log)
[Ryujinx_1.1.1340_2024-07-06_16-50-04.log](https://github.com/user-attachments/files/16115524/Ryujinx_1.1.1340_2024-07-06_16-50-04.log)
[Ryujinx_1.1.1340_2024-07-06_14-56-52.log](https://github.com/user-attachments/files/16115525/Ryujinx_1.1.1340_2024-07-06_14-56-52.log)

**Comment by piplup55** [comment] 2024-07-06 09:50
duplicate of #3817

**Closed by piplup55** 2024-07-06 09:50 UTC
