### ISSUE TITLE
ARCropolis for Super Smash Bros. Ultimate doesn't work.

### ISSUE THREAD

**Issue by mrTerryBogard** [Ryujinx/Ryujinx-Games-List#4948] opened 2024-05-01 10:37 UTC
### Game Name

Super Smash Bros. Ultimate [01006A800016E000]

### Game Update Version

v1835008

### Emulator Build Version

1.1.1295

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

[15.6" Laptop Neobihier ZX-I7-10750H, Intel Core i7-10750H (2.6 GHz), RAM 16 GB, SSD 1024 GB Intel UHD Graphics 630, Windows 11 Pro, Russian keyboard]

### Game State

I didn't understand what to write.

But I assure you that I talked today with the author of the [Guide] ARCropolis Mods using Ryujinx Emulator [https://gamebanana.com/tuts/14311](url) and he also didn’t understand why it didn’t work for me, but his last words sounded like this:

> Yea. The placementt are correct. I guess it's either ARCropolis or Ryujinx made an oopsie. Your best option is the Ryujinx Discord to figure out the problem. Let them know that you have everything set up. It's just legacy_discovery not working.

### Log File

In this case, in principle, something that the game does not see cannot have logs. This is ARCropolis..

**Comment by piplup55** [comment] 2024-05-01 11:38
duplicate of #136

**Closed by piplup55** 2024-05-01 11:38 UTC
